import {
  FileText,
  ShoppingCart,
  Package,
  BarChart3,
  Users,
  Truck,
  Receipt,
  Smartphone,
  Wallet,
  Wrench,
  Signal,
  Banknote,
  Target,
  AlarmClock,
  ClipboardList,
  HandCoins,
  Landmark,
  ClipboardEdit,
  Handshake,
  ArrowLeftRight,
  Bell,
  BookOpen,
  Bot,
  Building2,
  GraduationCap,
  MessageCircle,
  NotebookText,
  PiggyBank,
  QrCode,
  Scale,
  ShieldCheck,
  Sparkles,
  TrendingDown,
  TrendingUp,
  UserCog,
  Users2,
  WalletCards,
  LinkIcon,
  DollarSign,
  LayoutGrid,
  CalendarCheck,
  Activity,
} from 'lucide-react'
import {
  IconBarcode,
  IconBook,
  IconBuilding,
  IconBuildingStore,
  IconCalendar,
  IconCalendarEvent,
  IconCash,
  IconCategory,
  IconChartBar,
  IconChecklist,
  IconClipboardCheck,
  IconClock,
  IconCreditCard,
  IconCrown,
  IconFileImport,
  IconHistory,
  IconId,
  IconLayoutDashboard,
  IconPackages,
  IconRefresh,
  IconReportAnalytics,
  IconSchool,
  IconSettings,
  IconShield,
  IconTag,
  IconTransfer,
  IconUsers,
  IconUsersGroup,
} from '@tabler/icons-react'

/**
 * Resolves the `iconKey` string returned by the /quick-links API (sourced from
 * server/src/config/quick-link-registry.js) to an actual icon component. Everywhere
 * else in this app an icon is a component reference, never a persisted string — this
 * map is the one deliberate exception, needed because Quick Links icons are chosen by
 * the *user* through a DB-backed list, not hardcoded in a TSX file. Both icon
 * libraries the app already uses (lucide-react and @tabler/icons-react, matching
 * whichever one sidebar-data.ts itself picked for that nav item) are supported here so
 * a Quick Link shows the exact same icon as its sidebar entry. Add an entry here
 * whenever a new `iconKey` is added to the server registry.
 *
 * Typed as `React.ElementType` (same as `BaseNavItem.icon` in
 * components/layout/types.ts) rather than lucide's own `LucideIcon` — lucide and
 * tabler icon components aren't structurally assignable to each other (their forwarded
 * `ref` types differ), and every call site here only ever renders `<Icon
 * className={...} />`, which both satisfy.
 */
export const QUICK_LINK_ICON_MAP: Record<string, React.ElementType> = {
  FileText,
  ShoppingCart,
  Package,
  BarChart3,
  Users,
  Truck,
  Receipt,
  Smartphone,
  Wallet,
  Wrench,
  Signal,
  Banknote,
  Target,
  AlarmClock,
  ClipboardList,
  HandCoins,
  Landmark,
  ClipboardEdit,
  Handshake,
  ArrowLeftRight,
  Bell,
  BookOpen,
  Bot,
  Building2,
  GraduationCap,
  MessageCircle,
  NotebookText,
  PiggyBank,
  QrCode,
  Scale,
  ShieldCheck,
  Sparkles,
  TrendingDown,
  TrendingUp,
  UserCog,
  Users2,
  WalletCards,
  DollarSign,
  LayoutGrid,
  CalendarCheck,
  Activity,
  IconBarcode,
  IconBook,
  IconBuilding,
  IconBuildingStore,
  IconCalendar,
  IconCalendarEvent,
  IconCash,
  IconCategory,
  IconChartBar,
  IconChecklist,
  IconClipboardCheck,
  IconClock,
  IconCreditCard,
  IconCrown,
  IconFileImport,
  IconHistory,
  IconId,
  IconLayoutDashboard,
  IconPackages,
  IconRefresh,
  IconReportAnalytics,
  IconSchool,
  IconSettings,
  IconShield,
  IconTag,
  IconTransfer,
  IconUsers,
  IconUsersGroup,
}

export const resolveQuickLinkIcon = (iconKey: string): React.ElementType => QUICK_LINK_ICON_MAP[iconKey] || LinkIcon
