import { createFileRoute } from '@tanstack/react-router'
import { z } from 'zod'
import InvoicePage from '@/features/invoice'

const invoiceSearchSchema = z.object({
  view: z.enum(['list', 'create', 'convert-pending']).optional(),
  type: z.string().optional(),
})

// @ts-ignore - Route will be generated by TanStack Router plugin
export const Route = createFileRoute('/_authenticated/invoice/')({
  component: InvoicePage,
  validateSearch: invoiceSearchSchema,
})
