import { createFileRoute } from '@tanstack/react-router'
import InvoicePage from '@/features/invoice'

// @ts-ignore - Route will be generated by TanStack Router plugin
export const Route = createFileRoute('/_authenticated/invoice/')({
  component: InvoicePage,
})
