import { createFileRoute } from '@tanstack/react-router'
import PurchaseReturnsPage from '@/features/purchase-returns'

// @ts-ignore - Route will be generated by TanStack Router plugin
export const Route = createFileRoute('/_authenticated/purchase-returns/')({
  component: PurchaseReturnsPage,
})
