import {
  Archive,
  Award,
  BadgeCheck,
  BarChart3,
  Bell,
  BookOpen,
  Building2,
  Calendar,
  Check,
  ChefHat,
  ClipboardList,
  Clock,
  Cloud,
  Coins,
  CreditCard,
  EyeOff,
  FileText,
  Headset,
  Landmark,
  Languages,
  Layers,
  LayoutGrid,
  Lock,
  MessageCircle,
  Package,
  Percent,
  QrCode,
  Receipt,
  RefreshCw,
  ScanBarcode,
  Search,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Smartphone,
  Tag,
  Truck,
  Undo2,
  Upload,
  Users,
  UserX,
  Wallet,
  Wrench,
  Zap,
  type LucideProps,
} from "lucide-react";

const ICONS = {
  archive: Archive,
  award: Award,
  badge: BadgeCheck,
  bank: Landmark,
  bell: Bell,
  book: BookOpen,
  building: Building2,
  calendar: Calendar,
  card: CreditCard,
  cart: ShoppingCart,
  chart: BarChart3,
  check: Check,
  chef: ChefHat,
  clipboard: ClipboardList,
  clock: Clock,
  cloud: Cloud,
  coins: Coins,
  eyeoff: EyeOff,
  file: FileText,
  grid: LayoutGrid,
  headset: Headset,
  languages: Languages,
  layers: Layers,
  lock: Lock,
  message: MessageCircle,
  package: Package,
  percent: Percent,
  qr: QrCode,
  receipt: Receipt,
  refresh: RefreshCw,
  scan: ScanBarcode,
  search: Search,
  shield: ShieldCheck,
  sliders: SlidersHorizontal,
  smartphone: Smartphone,
  sparkles: Sparkles,
  tag: Tag,
  truck: Truck,
  undo: Undo2,
  upload: Upload,
  users: Users,
  userx: UserX,
  wallet: Wallet,
  wrench: Wrench,
  zap: Zap,
} as const;

export type IconName = keyof typeof ICONS;

export default function Icon({ name, ...props }: { name: IconName } & LucideProps) {
  const Cmp = ICONS[name];
  return <Cmp aria-hidden {...props} />;
}
