import { createFileRoute } from '@tanstack/react-router'
import SalesReturnsPage from '@/features/sales-returns'

// @ts-ignore - Route will be generated by TanStack Router plugin
export const Route = createFileRoute('/_authenticated/sales-returns/')({
  component: SalesReturnsPage,
})
