import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Printer, X } from 'lucide-react'

export type MobileReceiptLine = { label: string; value: string }

export type MobileReceiptData = {
  title: string
  /** Shown under title (e.g. batch summary) */
  subtitle?: string
  reference?: string
  issuedAt?: string
  lines: MobileReceiptLine[]
}

/** Print layout is generated by `printMobileShopReceipt` (invoice-style HTML + browser print dialog). */

export function MobileReceiptOffer({
  onPrint,
  onDismiss,
  children,
}: {
  onPrint: () => void
  onDismiss: () => void
  children?: React.ReactNode
}) {
  return (
    <Card className='mb-4 border-primary/30 bg-primary/5'>
      <CardContent className='flex flex-wrap items-center justify-between gap-3 py-3'>
        <p className='text-sm text-foreground'>
          {children ?? 'Saved successfully. Print a receipt for the customer.'}
        </p>
        <div className='flex shrink-0 gap-2'>
          <Button type='button' size='sm' variant='default' onClick={onPrint}>
            <Printer className='mr-1.5 h-3.5 w-3.5' />
            Print receipt
          </Button>
          <Button type='button' size='sm' variant='outline' onClick={onDismiss}>
            <X className='mr-1 h-3.5 w-3.5' />
            Dismiss
          </Button>
        </div>
      </CardContent>
    </Card>
  )
}

export function fmtRs(n: number) {
  return `Rs ${Number(n).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
}
