import { useMemo, useState } from 'react'
import { ArrowDownCircle, ArrowUpCircle, NotebookText, Wallet } from 'lucide-react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { StatCard } from '@/features/dashboard/components/stat-card'
import { MobilePageShell } from '../components/mobile-page-shell'
import { useGetCashBookEntriesQuery, useGetCashBookSummaryQuery } from '@/stores/mobile-shop.api'

const formatDateInput = (date: Date) => {
  const year = date.getFullYear()
  const month = `${date.getMonth() + 1}`.padStart(2, '0')
  const day = `${date.getDate()}`.padStart(2, '0')
  return `${year}-${month}-${day}`
}

export default function CashBookPage() {
  const today = useMemo(() => formatDateInput(new Date()), [])
  const [startDate, setStartDate] = useState(today)
  const [endDate, setEndDate] = useState(today)

  const queryParams = useMemo(() => {
    if (!startDate || !endDate) {
      return undefined
    }
    // Parse as local date (not UTC) so midnight = local midnight regardless of timezone
    const [sy, sm, sd] = startDate.split('-').map(Number)
    const [ey, em, ed] = endDate.split('-').map(Number)
    const start = new Date(sy, sm - 1, sd, 0, 0, 0, 0)
    const end = new Date(ey, em - 1, ed, 23, 59, 59, 999)
    return {
      startDate: start.toISOString(),
      endDate: end.toISOString(),
    }
  }, [startDate, endDate])

  const { data: summary } = useGetCashBookSummaryQuery(queryParams)
  const { data: entries } = useGetCashBookEntriesQuery(queryParams)

  const setTodayFilter = () => {
    const value = formatDateInput(new Date())
    setStartDate(value)
    setEndDate(value)
  }

  const setYesterdayFilter = () => {
    const date = new Date()
    date.setDate(date.getDate() - 1)
    const value = formatDateInput(date)
    setStartDate(value)
    setEndDate(value)
  }

  const setLast7DaysFilter = () => {
    const end = new Date()
    const start = new Date()
    start.setDate(end.getDate() - 6)
    setStartDate(formatDateInput(start))
    setEndDate(formatDateInput(end))
  }

  const clearDateFilter = () => {
    setStartDate('')
    setEndDate('')
  }

  return (
    <MobilePageShell
      title='Cash Book'
      description='A central ledger of all income and expense entries generated by mobile-shop modules.'
    >
      <Card>
        <CardHeader>
          <CardTitle>Date Filter</CardTitle>
        </CardHeader>
        <CardContent className='space-y-4'>
          <div className='grid gap-4 md:grid-cols-2'>
            <div className='space-y-2'>
              <Label htmlFor='cashbook-start-date'>Start Date</Label>
              <Input
                id='cashbook-start-date'
                type='date'
                value={startDate}
                onChange={(event) => setStartDate(event.target.value)}
              />
            </div>
            <div className='space-y-2'>
              <Label htmlFor='cashbook-end-date'>End Date</Label>
              <Input
                id='cashbook-end-date'
                type='date'
                value={endDate}
                onChange={(event) => setEndDate(event.target.value)}
              />
            </div>
          </div>

          <div className='flex flex-wrap gap-2'>
            <Button type='button' variant='outline' size='sm' onClick={setTodayFilter}>Today</Button>
            <Button type='button' variant='outline' size='sm' onClick={setYesterdayFilter}>Yesterday</Button>
            <Button type='button' variant='outline' size='sm' onClick={setLast7DaysFilter}>Last 7 Days</Button>
            <Button type='button' variant='ghost' size='sm' onClick={clearDateFilter}>All Time</Button>
          </div>
        </CardContent>
      </Card>

      <div className='grid gap-4 sm:grid-cols-2 xl:grid-cols-3'>
        <StatCard
          title='Total Income'
          value={summary?.totalIncome || 0}
          icon={<ArrowUpCircle className='h-4 w-4' />}
          valuePrefix='Rs '
          description='Cash book income entries'
        />
        <StatCard
          title='Total Expense'
          value={summary?.totalExpense || 0}
          icon={<ArrowDownCircle className='h-4 w-4' />}
          valuePrefix='Rs '
          description='Cash book expense entries'
        />
        <StatCard
          title='Net Cash Flow'
          value={(summary?.totalIncome || 0) - (summary?.totalExpense || 0)}
          icon={<Wallet className='h-4 w-4' />}
          valuePrefix='Rs '
          description='Income minus expense'
        />
      </div>

      <Card className='mt-6'>
        <CardHeader>
          <CardTitle className='flex items-center gap-2'>
            <NotebookText className='h-5 w-5' />
            Cash Book Entries
          </CardTitle>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Date</TableHead>
                <TableHead>Source</TableHead>
                <TableHead>Payment</TableHead>
                <TableHead className='text-red-600'>Debit (Expense)</TableHead>
                <TableHead className='text-green-600'>Credit (Income)</TableHead>
                <TableHead>Description</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {(entries?.results ?? []).map((entry) => (
                <TableRow key={entry.id}>
                  <TableCell>{new Date(entry.date).toLocaleString()}</TableCell>
                  <TableCell className='capitalize'>{entry.source}</TableCell>
                  <TableCell className='capitalize'>{entry.paymentMethod}</TableCell>
                  <TableCell className='text-red-600'>
                    {entry.type === 'expense' ? `Rs ${entry.amount.toLocaleString()}` : '-'}
                  </TableCell>
                  <TableCell className='text-green-600'>
                    {entry.type === 'income' ? `Rs ${entry.amount.toLocaleString()}` : '-'}
                  </TableCell>
                  <TableCell>{entry.description || 'No description'}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </MobilePageShell>
  )
}