import { createFileRoute } from '@tanstack/react-router'
import PurchaseOrdersPage from '@/features/purchase-orders'

// @ts-ignore - Route will be generated by TanStack Router plugin
export const Route = createFileRoute('/_authenticated/purchase-orders/')({
  component: PurchaseOrdersPage,
})
