import { createFileRoute } from '@tanstack/react-router'
import { z } from 'zod'
import PurchaseOrdersPage from '@/features/purchase-orders'

const purchaseOrdersSearchSchema = z.object({
  prefillItems: z
    .array(z.object({ productId: z.string(), variantId: z.string().optional(), quantity: z.number() }))
    .optional(),
  supplierId: z.string().optional(),
})

// @ts-ignore - Route will be generated by TanStack Router plugin
export const Route = createFileRoute('/_authenticated/purchase-orders/')({
  component: PurchaseOrdersPage,
  validateSearch: purchaseOrdersSearchSchema,
})
