import { createContext, useContext, useEffect, useState, ReactNode } from 'react'

// Define our supported languages
type Language = 'en' | 'ur'

// Define our translations
interface TranslationDictionary {
  [key: string]: string;
}

interface Translations {
  en: TranslationDictionary;
  ur: TranslationDictionary;
}

const translations: Translations = {
  en: {
    // General Search and Command Menu
    "search": "Search",
    "search_placeholder": "Type a command or search...",
    "no_results_found": "No results found.",
    "theme": "Theme",
    "light": "Light",
    "dark": "Dark",
    "system": "System",
    
    // Dashboard
    "dashboard": "Dashboard",
    "download": "Download",
    "overview": "Overview",
    "analytics": "Analytics",
    "reports": "Reports",
    "notifications": "Notifications",
    "total_revenue": "Total Revenue",
    "subscriptions": "Subscriptions",
    "sales": "Sales",
    "active_now": "Active Now",
    "from_last_month": "from last month",
    "since_last_hour": "since last hour",
    "recent_sales": "Recent Sales",
    "sales_this_month": "You made 265 sales this month.",
    "revenue_overview": "Revenue Overview",
    "revenue_chart_description": "Track your revenue and profit trends",
    "Today": "Today",
    "This Week": "This Week",
    "This Month": "This Month",
    "This Year": "This Year",
    "Revenue": "Revenue",
    "Profit": "Profit",
    "Low Stock Alerts": "Low Stock Alerts",
    "out_of_stock": "Out of Stock",
    "low_stock": "Low Stock",
    "all_products_well_stocked": "All products are well stocked!",
    "view_all_products": "View All Products",
    "units_sold": "units sold",
    "in_stock": "in stock",
    "Top Selling Products": "Top Selling Products",
    "Top Customers": "Top Customers",
    "purchases": "purchases",
    "Recent Activities": "Recent Activities",
    "Quick Actions": "Quick Actions",
    "Create Invoice": "Create Invoice",
    "Add Purchase": "Add Purchase",
    "Add Product": "Add Product",
    "View Reports": "View Reports",
    "Refresh Dashboard": "Refresh Dashboard",
    "Business Overview": "Business Overview",
    "Total Sales": "Total Sales",
    "Low Stock Products": "Low Stock Products",
    "Pending Invoices": "Pending Invoices",
    "vs_last_month": "vs last month",
    
    // Reports
    "reports_description": "View and analyze all your business reports",
    "date_range": "Date Range",
    "select_date_range_for_reports": "Select date range for reports",
    "start_date": "Start Date",
    "end_date": "End Date",
    "pick_date": "Pick a date",
    "refresh": "Refresh",
    "export": "Export",
    "today": "Today",
    "last_7_days": "Last 7 Days",
    "last_30_days": "Last 30 Days",
    "profit_loss": "Profit & Loss",
    "inventory": "Inventory",
    "tax": "Tax",
    "sales_trend": "Sales Trend",
    "daily_sales_and_profit": "Daily sales and profit overview",
    "detailed_sales_data": "Detailed Sales Data",
    "date": "Date",
    "invoices": "Invoices",
    "cost": "Cost",
    "profit": "Profit",
    "margin": "Margin",
    "total_profit": "Total Profit",
    "total_invoices": "Total Invoices",
    "avg_invoice_value": "Avg Invoice Value",
    "total_purchases": "Total Purchases",
    "total_paid": "Total Paid",
    "balance_due": "Balance Due",
    "purchase_details": "Purchase Details",
    "supplier": "Supplier",
    "count": "Count",
    "amount": "Amount",
    "paid": "Paid",
    "balance": "Balance",
    "total_products": "Total Products",
    "stock_value": "Stock Value",
    "top_selling_products": "Top Selling Products",
    "product": "Product",
    "category": "Category",
    "quantity_sold": "Quantity Sold",
    "revenue": "Revenue",
    "current_stock": "Current Stock",
    "unique_customers": "Unique Customers",
    "avg_transaction": "Avg Transaction",
    "top_customers": "Top Customers",
    "customer": "Customer",
    "phone": "Phone",
    "total_spent": "Total Spent",
    "avg_purchase": "Avg Purchase",
    "last_purchase": "Last Purchase",
    "supplier_analysis": "Supplier Analysis",
    "total_amount": "Total Amount",
    "total_expenses": "Total Expenses",
    "expense_count": "Expense Count",
    "avg_expense": "Avg Expense",
    "expense_by_category": "Expense by Category",
    "revenue_section": "Revenue Section",
    "cost_of_goods_sold": "Cost of Goods Sold",
    "gross_profit": "Gross Profit",
    "expenses_section": "Expenses Section",
    "net_profit_loss": "Net Profit / Loss",
    "net_profit": "Net Profit",
    "net_margin": "Net Margin",
    "inventory_details": "Inventory Details",
    "all_products": "All Products",
    "stock": "Stock",
    "value": "Value",
    "status": "Status",
    "total_tax_collected": "Total Tax Collected",
    "monthly_tax_summary": "Monthly Tax Summary",
    "month": "Month",
    "tax_collected": "Tax Collected",
    
    // User Profile and Authentication
    "upgrade_to_pro": "Upgrade to Pro",
    "account": "Account",
    "profile": "Profile",
    "billing": "Billing",
    "settings": "Settings",
    "new_team": "New Team",
    "log_out": "Log out",
    "logout_success": "Logout successfully!",
    
    // Suppliers page
    "suppliers_list": "Suppliers List",
    "manage_suppliers": "Manage your Suppliers here.",
    "search_suppliers": "Search suppliers...",
    "add_supplier": "Add Supplier",
    "edit_supplier": "Edit Supplier",
    "delete_supplier": "Delete Supplier",
    "supplier_name": "Supplier Name",
    
    // Customers page
    "customers_list": "Customers List",
    "manage_customers": "Manage your Customers here.",
    "search_customers": "Search customers...",
    "search_customers_by_name_or_phone": "Search by name or phone...",
    "filter_customers": "Filter Customers...",
    "add_customer": "Add Customer",
    "edit_customer": "Edit Customer",
    "delete_customer": "Delete Customer",
    "customer_name": "Customer Name",
    "enter_customer_name": "Enter customer name",
    "no_customers_found": "No customers found",
    
    // Products page
    "products_list": "Products List",
    "manage_products": "Manage your Products here.",
    "search_products": "Search products...",
    "search_categories": "Search categories...",
    "filter_products": "Filter Products...",
    "add_product": "Add Product",
    "edit_product": "Edit Product",
    "delete_product": "Delete Product",
    "product_name": "Product Name",
    "description": "Description",
    "barcode": "Barcode",
    "price": "Price",
    "stock_quantity": "Stock Quantity",
    "qty": "Qty",
    
    // Product CRUD operations
    "product_created_successfully": "Product created successfully",
    "product_updated_successfully": "Product updated successfully",
    "product_deleted_successfully": "Product deleted successfully",
    "update_product_description": "Update the product here. Click save when you're done.",
    "create_product_description": "Create new product here. Click save when you're done.",
    
    // Delete dialog
    "delete_product_confirmation": "Are you sure you want to delete",
    "delete_product_warning": "This action will permanently remove the product of",
    "delete_product_warning_suffix": "from the system. This cannot be undone.",
    "delete_product_placeholder": "Enter Product to confirm deletion.",
    "delete_operation_warning": "Please be careful, this operation can not be rolled back.",
    
    // Bulk Edit Products
    "bulk_edit_products": "Bulk Edit Products",
    "bulk_edit_selected": "Bulk Edit Selected",
    "edit_selected_products": "Edit {count} selected products",
    "enter_new_price": "Enter new price (leave empty to keep current)",
    "enter_new_cost": "Enter new cost (leave empty to keep current)",
    "enter_new_quantity": "Enter new quantity (leave empty to keep current)",
    "update_products": "Update Products",
    "bulk_update_success": "Successfully updated",
    "no_products_selected": "No products selected",
    "select_products_first": "Please select products first",
    "enter_at_least_one_value": "Please enter at least one value to update",
    "no_changes_to_update": "No changes to update",
    "enter_new": "Enter new",
    "current": "Current",
    // "bulk_update_success": "Products updated successfully!",
    
    // Low Stock Alert System
    "low_stock_alert": "Low Stock Alert",
    "low_stock_alerts_disabled": "Low stock alerts are disabled",
    "enable_alerts": "Enable Alerts",
    // "all_products_well_stocked": "All products are well stocked",
    "products_need_attention": "Some products need your attention",
    // "out_of_stock": "Out of Stock",
    "critical_stock": "Critical Stock",
    // "low_stock": "Low Stock",
    "critical": "Critical",
    "out_of_stock_products": "Out of Stock Products",
    "critical_stock_products": "Critical Stock Products",
    "low_stock_products": "Low Stock Products",
    "and": "and",
    "more": "more",
    "left": "left",
    "less_than": "Less than",
    "units": "units",
    "showing": "Showing",
    "products": "products",
    "low_stock_alert_settings": "Low Stock Alert Settings",
    "configure_low_stock_threshold": "Configure when to show low stock warnings",
    "low_stock_threshold": "Low Stock Threshold",
    "alert_when_stock_below_threshold": "Alert when product stock falls below this number",
    "enable_notifications": "Enable Notifications",
    "enabled": "Enabled",
    "disabled": "Disabled",
    "save_settings": "Save Settings",
    "products_need_immediate_restock": "Products need immediate restocking",
    "less_than_x_units": "Less than {count} units",
    "below_threshold": "Below threshold",
    "products_requiring_restock": "Products requiring restocking attention",
    "search_by_name_or_barcode": "Search by name or barcode",
    "filter_by_status": "Filter by status",
    "all": "All",
    "no_low_stock_products": "No low stock products",
    "showing_x_products": "Showing {count} products",
    "export_csv": "Export CSV",
    "back": "Back",
    "no_items": "No items",
    
    // Barcode functionality
    "scan_barcode": "Scan Barcode",
    "enter_barcode": "Enter Barcode",
    "barcode_scanner": "Barcode Scanner",
    "barcode_input": "Barcode Input",
    "barcode_scanned": "Barcode Scanned",
    "barcode_entered": "Barcode Entered",
    "enter_or_scan_barcode": "Enter or scan barcode...",
    "point_camera_at_barcode": "Point camera at barcode to scan",
    "camera_access_failed": "Camera access failed. Please check permissions.",
    "try_again": "Try Again",
    "cancel": "Cancel",
    "add": "Add",
    "use_scanner_gun": "Use Scanner Gun",
    "stop_scanner": "Stop Scanner",
    "scanner_ready": "Scanner ready - scan a barcode",
    "scanner_listening": "Listening for barcode scanner...",
    "scanner_instructions": "Use your barcode gun or type manually",
    "barcode_product_search": "Barcode Product Search",
    "enter_barcode_to_search": "Enter barcode to search...",
    "product_found": "Product Found",
    "product_not_found": "Product Not Found",
    
    // Invoice functionality
    "create_invoice": "Create Invoice",
    "create_new_invoice": "Create a new invoice",
    "invoice_details": "Invoice Details",
    "invoice_items": "Invoice Items",
    "add_item": "Add Item",
    "select_product": "Select Product",
    "select_product_for_manual_entries": "Please select a product for all manual entries before saving",
    "product_catalog": "Product Catalog",
    "invoice_type": "Invoice Type",
    "select_customer": "Select Customer",
    "walk_in_customer": "Walk-in Customer",
    "cash": "Cash",
    "credit": "Credit",
    "pending": "Pending",
    "due_date": "Due Date",
    "no_items_added": "No items added to invoice yet",
    "subtotal": "Subtotal",
    "discount": "Discount",
    "tax_rate": "Tax Rate",
    "total": "Total",
    "type": "Type",
    "paid_amount": "Paid Amount",
    "notes": "Notes",
    "add_notes": "Add notes or comments...",
    "save_invoice": "Save Invoice",
    "update_invoice": "Update Invoice",
    "save_and_print": "Save & Print",
    "save_and_print_receipt": "Save & Print Receipt",
    "save_and_print_a4": "Save & Print A4",
    "update_and_print_receipt": "Update & Print Receipt",
    "update_and_print_a4": "Update & Print A4",
    "print_success": "Invoice sent to printer",
    "print_error": "Failed to print invoice",
    "saving": "Saving",
    
    // Print Template Translations
    "print_business_name": "Your Business Name",
    "print_business_address": "123 Business Street, City, State 12345",
    "print_business_phone": "Phone: (555) 123-4567",
    "print_business_email": "Email: info@business.com",
    "print_tax_id": "Tax ID: 123-456-789",
    "print_invoice_title": "INVOICE",
    "print_time": "Time",
    "print_bill_to": "Bill To",
    "print_invoice_details": "Invoice Details",
    "print_issue_date": "Issue Date",
    "print_items_count": "Items Count",
    "print_items_purchased": "ITEMS PURCHASED",
    "print_product_name": "Product Name",
    "print_unit_price": "Unit Price",
    "print_quantity": "Quantity",
    "print_paid_in_full": "PAID IN FULL",
    "print_balance_due": "Balance Due",
    "print_paid": "Paid",
    "print_invoice_barcode": "Invoice Barcode",
    "print_scan_to_verify": "Scan to verify invoice",
    "print_additional_notes": "Additional Notes",
    "print_thank_you_message": "Thank you for your business!",
    "print_keep_receipt": "Please keep this receipt for your records",
    "print_visit_again": "Visit us again soon",
    "print_receipt_btn": "Print Receipt",
    "print_invoice_btn": "Print Invoice",
    "print_close": "Close",
    "print_options": "Print Options",
    "print_payment_information": "Payment Information",
    "print_payment_status": "Payment Status",
    "print_completed": "COMPLETED",
    "print_pending_payment": "PENDING PAYMENT",
    "print_powered_by": "Powered by Your POS System",
    "print_delivery_charge": "Delivery Charge",
    "print_service_charge": "Service Charge",
    "print_amount_paid": "Amount Paid",
    "print_generated_on": "Generated on",
    
    // Barcode
    "generate": "Generate",
    "barcode_generated": "Barcode generated successfully",
    
    // Payment Receipt
    "Payment Receipt": "Payment Receipt",
    "Generate Receipt": "Generate Receipt",
    "Print Receipt": "Print Receipt",
    "Receipt No": "Receipt No",
    "Received From": "Received From",
    "Payment Date": "Payment Date",
    "Previous Balance": "Previous Balance",
    "Payment Received": "Payment Received",
    "Remaining Balance": "Remaining Balance",
    "Received By": "Received By",
    "Customer Signature": "Customer Signature",
    "This is a computer generated receipt": "This is a computer generated receipt",
    "Thank you for your payment": "Thank you for your payment",
    
    // Pending Invoice Converter
    "convert_pending_invoices": "Convert Pending Invoices",
    "select_pending_invoices_to_convert_to_credit": "Select pending invoices to convert to credit",
    "please_select_customer_and_invoices": "Please select a customer and at least one invoice",
    "no_items_to_convert": "No items to convert",
    "credit_invoice_created_successfully": "Credit invoice created successfully",
    "failed_to_create_invoice": "Failed to create invoice",
    "no_pending_invoices_found": "No pending invoices found for this customer",
    "loading_invoices": "Loading invoices...",
    "pending_invoices": "Pending Invoices",
    "select_all": "Select All",
    "deselect_all": "Deselect All",
    "merged_items": "Merged Items",
    "from": "from",
    "items": "items",
    // "due_date": "Due Date",
    "invoice_date": "Invoice Date",
    "enter_notes": "Enter notes (optional)",
    "create_and_print_receipt": "Create & Print Receipt",
    "create_and_print_a4": "Create & Print A4",
    "create_without_printing": "Create Without Printing",

    // Product History
    "product_price_history": "Product Price History",
    "loading_history": "Loading history...",
    "error_loading_history": "Error loading history",
    "no_purchase_history": "No purchase history found",
    "this_is_first_purchase": "This is the first purchase of this product for this customer",
    "last_price": "Last Price",
    "current_price": "Current Price",
    "total_quantity": "Total Quantity",
    "same_price": "Same Price",
    "increase": "Increase",
    "decrease": "Decrease",
    "compared_to_last_purchase": "compared to last purchase",
    "purchase_history": "Purchase History",
    "latest": "Latest",
    "than_previous": "than previous",
    // "more": "more",
    "less": "less",
    "average_price": "Average Price",
    "min_price": "Min Price",
    "max_price": "Max Price",
    "view_history": "View History",
    "creating": "Creating...",
    "print_failed": "Print failed",
    
    // Enhanced Pending Invoice Converter
    "pending_only": "Pending Only",
    "converted_only": "Converted Only", 
    "all_invoices": "All Invoices",
    "converted_invoices": "Converted Invoices",
    "no_converted_invoices_found": "No converted invoices found",
    "converted": "Converted",
    "converted_on": "converted on",
    "converted_pending": "Converted Pending",
    "filter_by_date_range": "Filter by Date Range",
    "from_date": "From Date",
    "to_date": "To Date",
    "new_credit_invoice_details": "New Credit Invoice Details",
    "details_for_new_credit_invoice": "Details for the new credit invoice to be created",
    "credit_invoice_date": "Credit Invoice Date",
    "credit_due_date": "Credit Due Date",
    "credit_invoice_notes": "Credit Invoice Notes",
    "enter_notes_for_credit_invoice": "Enter notes for credit invoice (optional)",
    
    // Invoice List
    "invoice_management": "Invoice Management",
    "manage_customer_invoices": "Manage customer invoices and payments",
    // "loading_invoices": "Loading invoices...",
    "error_loading_invoices": "Error loading invoices",
    "unknown_error": "Unknown error",
    "invoice_number": "Invoice #",
    "bill_number": "Bill #",
    "invoices_count": "Count",
    "all_statuses": "All statuses",
    "all_types": "All types",
    "draft": "Draft",
    "finalized": "Finalized",
    "cancelled": "Cancelled",
    "refunded": "Refunded",
    "clear_filters": "Clear Filters",
    "invoices_list": "Invoices List",
    "search_invoices_placeholder": "Invoice #, Phone #, Customer...",
    "show": "Show",
    "return_items": "Return Items",
    "no_invoices_found": "No invoices found",
    "customer_id": "Customer ID",
    "previous": "Previous",
    "next": "Next",
    "first": "First",
    "last": "Last",
    "unknown_customer": "Unknown Customer",
    "unit_price": "Unit Price",
    
    "loading_products": "Loading products...",
    "with_images": "With Images",
    "without_images": "Without Images",
    "scan_or_enter_barcode": "Scan or enter barcode...",
    "barcode_mode_active": "Barcode mode active",
    "press_enter_to_search": "Press Enter to search",
    "no_products_found": "No products found",
    "no_products_available": "No products available",
    "no_product_with_barcode": "No product found with barcode",
    "consider_adding_new_product": "Consider adding this as a new product",
    "search_error": "Search error occurred",
    "capture_barcode": "Capture Barcode",
    "enter_barcode_manually": "Enter barcode manually",
    "barcode_from_image": "Barcode from image",
    "scanned": "Scanned",
    "click_scanner_button_to_activate": "Click scanner button to activate",
    "clear": "Clear",
    
    // Mobile camera scanner
    "mobile_camera_scanner": "Mobile Camera Scanner",
    "scan_with_camera": "Scan with Camera",
    "scanning_for_barcode": "Scanning for barcode",
    "enter_barcode_manually_for_testing": "Enter barcode manually for testing",
    "enter_manually_instead": "Enter Manually Instead",
    "scanning_instructions": "Scanning Instructions",
    "hold_phone_steady": "Hold phone steady",
    "ensure_good_lighting": "Ensure good lighting",
    "barcode_should_fill_frame": "Barcode should fill the frame",
    "enter_manually": "Enter Manually",
    
    // New mobile scanner translations
    "point_camera_at_qr_or_barcode": "Point camera at QR code or barcode",
    "ensure_good_lighting_or_use_flashlight": "Ensure good lighting or use flashlight button",
    "align_code_within_frame": "Align code within the scanning frame",
    "detection_is_automatic": "Detection is automatic - no need to press capture",
    "supports_multiple_formats": "Supports QR codes, EAN, Code128, and more",
    "flashlight_turned_off": "Flashlight turned off",
    "flashlight_turned_on": "Flashlight turned on",
    "flashlight_not_available": "Flashlight not available on this device",
    "turn_off_flashlight": "Turn off flashlight",
    "turn_on_flashlight": "Turn on flashlight",
    "make_sure_to": "Make sure to",
    "allow_camera_permission": "Allow camera permission when prompted",
    "try_refreshing_page": "Try refreshing the page",
    "check_camera_not_used_by_other_app": "Check if camera is being used by another app",
    "initializing_scanner": "Initializing scanner...",
    "this_will_take_moment": "This will only take a moment",
    
    // Excel Import functionality
    "import_excel": "Import Excel",
    "import_products_from_excel": "Import Products from Excel",
    "upload_excel_file_to_import_products": "Upload an Excel file to bulk import products",
    "download_template_first": "Download the template first to see the required format",
    "download_template": "Download Template",
    "select_excel_file": "Select Excel File",
    "selected_file": "Selected file",
    "parse_and_validate": "Parse & Validate",
    "parsing": "Parsing",
    "validation_errors": "Validation Errors",
    "found_in_excel_file": "found in Excel file",
    "row": "Row",
    "field": "Field",
    "error": "Error",
    "file_parsed_successfully": "File parsed successfully",
    "products_ready_to_import": "products ready to import",
    "preview_first_products": "Preview (first 5 products)",
    "import_successful": "Import successful",
    "products_imported": "products imported",
    "no_products_to_import": "No products to import",
    "error_importing_products": "Error importing products",
    "please_select_file": "Please select a file",
    "invalid_file_type": "Invalid file type. Please select .xlsx, .xls, or .csv file",
    "file_is_empty": "The file is empty",
    "error_parsing_file": "Error parsing file",
    "template_downloaded": "Template downloaded successfully",
    "warning_existing_products": "Warning: Importing will add new products. Existing products with the same barcode will not be affected.",
    "importing": "Importing",
    "import": "Import",
    "product_name_required": "Product name is required",
    "price_required": "Price is required",
    "price_must_be_positive": "Price must be a valid positive number",
    "cost_required": "Cost is required",
    "cost_must_be_positive": "Cost must be a valid positive number",
    "stock_quantity_required": "Stock quantity is required",
    "stock_must_be_positive": "Stock quantity must be a valid positive number",
    "low_stock_must_be_positive": "Low stock threshold must be a valid positive number",
    "ready_to_import": "Ready to import",
    
    // Customer import functionality
    "import_customers_from_excel": "Import Customers from Excel",
    "upload_excel_file_to_import_customers": "Upload an Excel file to bulk import customers",
    "no_customers_to_import": "No customers to import",
    "error_importing_customers": "Error importing customers",
    "customer_name_required": "Customer name is required",
    "invalid_email_format": "Invalid email format",
    "balance_must_be_number": "Balance must be a valid number",
    "warning_importing_customers": "Warning: Importing will add new customers to your database.",
    
    // Supplier import functionality
    "import_suppliers_from_excel": "Import Suppliers from Excel",
    "upload_excel_file_to_import_suppliers": "Upload an Excel file to bulk import suppliers",
    "no_suppliers_to_import": "No suppliers to import",
    "error_importing_suppliers": "Error importing suppliers",
    "supplier_name_required": "Supplier name is required",
    "warning_importing_suppliers": "Warning: Importing will add new suppliers to your database.",
    "suppliers_plural": "suppliers",
    "importing_suppliers": "Importing suppliers...",
    
    // Image upload functionality
    "product_image": "Product Image",
    "upload_image": "Upload Image",
    "remove_image": "Remove Image",
    "drag_drop_image": "Drag & drop an image here",
    "or_click_to_select": "or click to select",
    "or_use_options_below": "or use the options below",
    "drop_image_here": "Drop image here",
    "uploading_image": "Uploading image...",
    "image_upload_failed": "Image upload failed",
    "image_uploaded_successfully": "Image uploaded successfully",
    "image_removed_successfully": "Image removed successfully",
    "image_load_failed": "Failed to load image",
    "select_file": "Select File",
    "take_photo": "Take Photo",
    "capture": "Capture",
    "switch_camera": "Switch Camera",
    "retry": "Retry",
    
    // Common fields
    "email": "Email",
    "whatsapp": "Whatsapp",
    "address": "Address",
    "actions": "Actions",
    "no_results": "No results.",
    "name_required": "Name is required.",
    
    // Table actions
    "edit": "Edit",
    "delete": "Delete",
    "asc": "Asc",
    "desc": "Desc",
    "hide": "Hide",
    "view": "View",
    "toggle_columns": "Toggle columns",
    "select": "Select",
    
    // Pagination
    "rows_per_page": "Rows per page",
    "page": "Page",
    "of": "of",
    "to": "to",
    "row_selected": "row(s) selected.",
    "Showing": "Showing",
    "First": "First",
    "Last": "Last",
    "Previous": "Previous",
    "Next": "Next",
    "Records per page": "Records per page",
    "Show": "Show",
    "suppliers": "suppliers",
    "entries": "entries",
    "expenses": "expenses",
    "Export to Excel": "Export to Excel",
    "Data exported successfully": "Data exported successfully",
    "Failed to export data": "Failed to export data",
    
    // Dialog content
    "update_supplier": "Update the Supplier here.",
    "create_supplier": "Create new Supplier here.",
    "update_customer": "Update the Customer here.",
    "create_customer": "Create new Customer here.",
    "click_save": "Click save when you're done.",
    "save_changes": "Save changes",
    "delete_confirmation": "Are you sure you want to delete",
    "delete_warning": "This action will permanently remove the supplier",
    "delete_customer_warning": "This action will permanently remove the customer",
    "from_system": "from the system. This cannot be undone.",
    "enter_name_confirm": "Enter Supplier Name to confirm deletion.",
    "enter_customer_name_confirm": "Enter Customer Name to confirm deletion.",
    "warning": "Warning!",
    "operation_warning": "Please be careful, this operation cannot be rolled back.",
    
    // Common UI components
    "loading": "Loading...",
    
    // Success Messages
    "supplier_created_success": "Supplier created successfully",
    "supplier_updated_success": "Supplier updated successfully",
    "supplier_deleted_success": "Supplier deleted successfully",
    "customer_created_success": "Customer created successfully",
    "customer_updated_success": "Customer updated successfully",
    "customer_deleted_success": "Customer deleted successfully",
    
    // Sidebar Navigation
    "general": "General",
    // "dashboard": "Dashboard",
    "customers": "Customers",
    "categories": "Categories",
    // "products": "Products",
    "purchase": "Purchase",
    // "invoices": "Invoices",
    "returns": "Returns",
    
    // Returns Management
    "returns_management": "Returns Management",
    "manage_returns": "Manage customer returns and refunds",
    "create_return": "Create Return",
    "new_return_request": "Create a new return request",
    "returns_list": "Returns List",
    "no_returns_found": "No returns found",
    "return_number": "Return Number",
    "original_invoice": "Original Invoice",
    "original_invoice_information": "Original Invoice Information",
    "invoice_details_prefilled": "Invoice details are pre-filled and cannot be modified",
    "return_date": "Return Date",
    "return_type": "Return Type",
    "return_status": "Return Status",
    "return_reason": "Return Reason",
    "refund_amount": "Refund Amount",
    "total_return_amount": "Total Return Amount",
    "restocking_fee": "Restocking Fee",
    "processing_fee": "Processing Fee",
    "receipt_required": "Receipt Required",
    "receipt_provided": "Receipt Provided",
    "refund_method": "Refund Method",
    "return_condition": "Condition",
    "restockable": "Restockable",
    "returned_quantity": "Returned Quantity",
    "return_amount": "Amount",
    "rejection_reason": "Rejection Reason",
    
    // Return Types
    "full_refund": "Full Refund",
    "partial_refund": "Partial Refund",
    "exchange": "Exchange",
    "store_credit": "Store Credit",
    
    // Return Status
    "return_pending": "Pending",
    "return_approved": "Approved",
    "return_rejected": "Rejected",
    "return_processed": "Processed",
    "return_completed": "Completed",
    
    // Refund Methods
    "refund_cash": "Cash",
    "refund_card": "Card",
    "original_payment": "Original Payment",
    
    // Item Conditions
    "condition_new": "New",
    "condition_used": "Used",
    "condition_damaged": "Damaged",
    "condition_defective": "Defective",
    
    // Return Reasons
    "reason_defective": "Defective",
    "wrong_item": "Wrong Item",
    "customer_request": "Customer Request",
    "reason_damaged": "Damaged",
    "reason_expired": "Expired",
    "reason_other": "Other",
    "select_reason": "Select Reason",
    "select_condition": "Select Condition",
    "reason": "Reason",
    "condition": "Condition",
    
    // Return Actions
    "approve_return": "Approve Return",
    "reject_return": "Reject Return",
    "fees_and_summary": "Fees and Summary",
    "original_qty": "Org Qty",
    "return_qty": "Return Qty",
    // "return_items": "Return Items",
    "items_from_invoice": "Items from Invoice",
    "restock": "Restock",
    "creating_return": "Creating Return",
    "final_refund_amount": "Final Refund Amount",
    "fees_exceed_return_amount": "Fees exceed return amount",
    "customer_may_owe_money": "Customer may owe money",
    "no_items_selected_for_return": "No items selected for return",
    "add_your_first_item": "Add Your First Item",
    "enter_return_reason": "Enter return reason...",
    "enter_additional_notes": "Enter additional notes...",
    "enter_rejection_reason": "Enter reason for rejection...",
    "select_return_type": "Select return type",
    "select_refund_method": "Select refund method",
    "skip_invoice_selection": "Skip Invoice Selection",
    "enter_invoice_number": "Enter invoice number",
    "search_by_invoice_or_customer": "Search by invoice number or customer name...",
    "process_return": "Process Return",
    "view_details": "View Details",
    "add_return_item": "Add Return Item",
    "remove_item": "Remove Item",
    "search_invoice": "Search Invoice",
    "select_invoice": "Select Invoice",
    "return_invoice_items": "Invoice Items",
    "return_details": "Return Details",
    "financial_summary": "Financial Summary",
    "return_created_successfully": "Return created successfully",
    "return_approved_successfully": "Return approved successfully",
    "return_rejected_successfully": "Return rejected successfully",
    "return_processed_successfully": "Return processed successfully",
    
    // Roles & Permissions
    "roles_permissions": "Roles & Permissions",
    "administration": "Administration",
    "roles_management": "Roles Management",
    "roles_management_description": "Manage user roles and permissions",
    "create_role": "Create Role",
    "edit_role": "Edit Role",
    "delete_role": "Delete Role",
    "role_name": "Role Name",
    "role_description": "Role Description",
    "permissions": "Permissions",
    "manage_permissions": "Manage Permissions",
    "all_roles": "All Roles",
    "roles_list_description": "View and manage all system roles",
    "no_roles_found": "No roles found",
    "role_created_successfully": "Role created successfully",
    "role_updated_successfully": "Role updated successfully",
    "role_deleted_successfully": "Role deleted successfully",
    "permissions_updated_successfully": "Permissions updated successfully",
    "system_role": "System Role",
    "custom_role": "Custom Role",
    "active": "Active",
    "inactive": "Inactive",
    "enter_role_name": "Enter role name",
    "enter_role_description": "Enter role description (optional)",
    "system_roles_cannot_be_deleted": "System roles cannot be deleted",
    "system_roles_cannot_be_modified": "System roles cannot be modified",
    "are_you_sure_delete_role": "Are you sure you want to delete this role?",
    "delete_role_warning": "This action cannot be undone. Users with this role will need to be reassigned.",
    "permission_groups": "Permission Groups",
    "main_permissions": "Main Permissions",
    "other_permissions": "Other Permissions",
    // "select_all": "Select All",
    // "deselect_all": "Deselect All",
    
    // Permission Categories
    "products_permissions": "Products",
    "invoices_permissions": "Invoices",
    "purchases_permissions": "Purchases",
    "customers_permissions": "Customers",
    "suppliers_permissions": "Suppliers",
    "categories_permissions": "Categories",
    "reports_permissions": "Reports",
    "users_permissions": "Users",
    "roles_permissions_group": "Roles",
    "settings_permissions": "Settings",
    "dashboard_permissions": "Dashboard",
    "payments_permissions": "Payments",
    
    // Individual Permissions
    "viewProducts": "View Products",
    "createProducts": "Create Products",
    "editProducts": "Edit Products",
    "deleteProducts": "Delete Products",
    "viewInvoices": "View Invoices",
    "createInvoices": "Create Invoices",
    "editInvoices": "Edit Invoices",
    "deleteInvoices": "Delete Invoices",
    "viewPurchases": "View Purchases",
    "createPurchases": "Create Purchases",
    "editPurchases": "Edit Purchases",
    "deletePurchases": "Delete Purchases",
    "viewCustomers": "View Customers",
    "createCustomers": "Create Customers",
    "editCustomers": "Edit Customers",
    "deleteCustomers": "Delete Customers",
    "viewSuppliers": "View Suppliers",
    "createSuppliers": "Create Suppliers",
    "editSuppliers": "Edit Suppliers",
    "deleteSuppliers": "Delete Suppliers",
    "viewCategories": "View Categories",
    "createCategories": "Create Categories",
    "editCategories": "Edit Categories",
    "deleteCategories": "Delete Categories",
    "viewReports": "View Reports",
    "exportReports": "Export Reports",
    "viewUsers": "View Users",
    "createUsers": "Create Users",
    "editUsers": "Edit Users",
    "deleteUsers": "Delete Users",
    "viewRoles": "View Roles",
    "createRoles": "Create Roles",
    "editRoles": "Edit Roles",
    "deleteRoles": "Delete Roles",
    "viewSettings": "View Settings",
    "editSettings": "Edit Settings",
    "viewDashboard": "View Dashboard",
    "managePayments": "Manage Payments",
    
    // Users Management
    "users_management": "Users Management",
    "users_management_description": "Manage users and assign roles",
    "all_users": "All Users",
    "users_list_description": "View and manage all system users",
    "no_users_found": "No users found",
    "create_user": "Create User",
    "edit_user": "Edit User",
    "delete_user": "Delete User",
    "user_created_successfully": "User created successfully",
    "user_updated_successfully": "User updated successfully",
    "user_deleted_successfully": "User deleted successfully",
    "failed_to_save_user": "Failed to save user",
    "failed_to_delete_user": "Failed to delete user",
    "enter_user_name": "Enter user name",
    "enter_email": "Enter email",
    "enter_password": "Enter password",
    "new_password": "New Password (optional)",
    "leave_blank_to_keep": "Leave blank to keep current",
    "select_role": "Select a role",
    "create_user_description": "Add a new user to the system and assign a role",
    "edit_user_description": "Update user information and assign a role",
    "delete_user_confirmation": "Are you sure you want to delete this user? This action cannot be undone.",
    "no_role": "No Role",
    "verified": "Verified",
    "not_verified": "Not Verified",
    "email_verified": "Email Verified",
    
    // "enter_return_reason": "Please enter a return reason",
    "add_items_to_return": "Please add items to return",
    "return_clear_filters": "Clear Filters",
    "return_all_statuses": "All statuses",
    "return_all_types": "All types",
    "loading_returns": "Loading returns...",
    "return_notes": "Notes",
    "accounts": "Accounts",
    "transactions": "Transactions",
    "mobile_repairing": "Mobile Repairing",
    "jazz_cash_&_load": "Jazz Cash & Load",
    // "reports": "Reports",
    "customers_ledger": "Customers Ledger",
    "suppliers_ledger": "Suppliers Ledger",
    "transaction_ledger": "Transaction Ledger",
    "sale_ledger": "Sale Ledger",
    "purchase_ledger": "Purchase Ledger",
    "account_ledger": "Account Ledger",

    // Categories page
    // "categories": "Categories",
    "manage_product_categories": "Manage your product categories here.",
    "add_category": "Add Category",
    "edit_category": "Edit Category",
    "delete_category": "Delete Category",
    "category_name": "Category Name",
    "category_image": "Category Image",
    "enter_category_name": "Enter category name",
    "enter_category_description": "Enter category description",
    "upload_category_image": "Upload category image",
    "optional": "Optional",
    
    // Category CRUD operations
    "category_created_successfully": "Category created successfully",
    "category_updated_successfully": "Category updated successfully",
    "category_deleted_successfully": "Category deleted successfully",
    "category_creation_failed": "Failed to create category",
    "category_update_failed": "Failed to update category",
    "category_deletion_failed": "Failed to delete category",
    "update_category_description": "Update the category here. Click save when you're done.",
    "create_category_description": "Create new category here. Click save when you're done.",
    "create_category": "Create Category",
    "update_category": "Update Category",
    "delete_category_confirmation": "Are you sure you want to delete this category",
    // "saving": "Saving...",
    "deleting": "Deleting...",
    "failed_to_load_categories": "Failed to load categories",
    "select_categories": "Select Categories",
    "no_categories_found": "No categories found",
    
    // Voice Input functionality
    "no_speech_detected": "No speech detected",
    "microphone_not_available": "Microphone not available",
    "microphone_permission_denied": "Microphone permission denied",
    "network_error_voice_recognition": "Network error during voice recognition",
    "voice_recognition_error": "Voice recognition error",
    "voice_recording_started": "Voice recording started",
    "failed_to_start_voice_recording": "Failed to start voice recording",
    "voice_recording_stopped": "Voice recording stopped",
    "start_voice_recording": "Start voice recording",
    "stop_voice_recording": "Stop voice recording",
    "voice_recognition_not_supported": "Voice recognition not supported in this browser",
    
    // Voice Input Demo
    "voice_input_demo": "Voice Input Demo",
    "test_voice_to_text_functionality": "Test voice to text functionality",
    "product_information": "Product Information",
    "voice_input_product_demo_description": "Try speaking to fill in product details",
    "speak_or_type_product_name": "Speak or type product name...",
    "speak_or_type_description": "Speak or type description...",
    "additional_notes": "Additional Notes",
    "speak_or_type_notes": "Speak or type notes...",
    "voice_input_results": "Voice Input Results",
    "see_converted_text_here": "See the converted text here",
    "no_text_entered": "No text entered yet",
    "voice_input_instructions": "Voice Input Instructions",
    "click_microphone_icon_to_start": "Click the microphone icon to start recording",
    "speak_clearly_into_microphone": "Speak clearly into your microphone",
    "voice_automatically_converts_to_text": "Voice will automatically convert to text",
    "click_microphone_again_to_stop": "Click the microphone icon again to stop recording",
    "note": "Note",
    "language_switches_automatically": "Language detection switches automatically based on your selected language",
    
    // Company Profile
    "company_profile": "Company Profile",
    "company_setup": "Company Setup",
    "manage_your_company_information": "Manage your company information",
    "setup_your_company_profile": "Setup your company profile to get started",
    "company_information": "Company Information",
    "update_your_company_details": "Update your company details",
    "enter_your_company_details_to_get_started": "Enter your company details to get started",
    "company_name": "Company Name",
    "tax_number": "Tax Number",
    "address_information": "Address Information",
    "change_password": "Change Password",
    "change_your_company_password": "Change your company password",
    "current_password": "Current Password",
    // "new_password": "New Password",
    "confirm_new_password": "Confirm New Password",
    "confirm_password": "Confirm Password",
    "changing": "Changing...",
    "create_company_profile": "Create Company Profile",
    "enter_company_name": "Enter company name",
    // "enter_email": "Enter email",
    // "enter_password": "Enter password",
    "enter_phone": "Enter phone number",
    "enter_tax_number": "Enter tax number",
    "enter_address": "Enter address",
    "enter_city": "Enter city",
    "enter_country": "Enter country",
    "Passwords do not match": "Passwords do not match",
    "Password must be at least 8 characters": "Password must be at least 8 characters",
    "Company profile updated successfully": "Company profile updated successfully",
    "Failed to update company profile": "Failed to update company profile",
    "Password changed successfully": "Password changed successfully",
    "Failed to change password": "Failed to change password",
    "Company profile created successfully": "Company profile created successfully",
    "Failed to create company profile": "Failed to create company profile",
  },
  ur: {
    // General Search and Command Menu
    "search": "تلاش کریں",
    "search_placeholder": "کمانڈ ٹائپ کریں یا تلاش کریں...",
    "no_results_found": "کوئی نتائج نہیں ملے۔",
    "theme": "تھیم",
    "light": "ہلکا",
    "dark": "گہرا",
    "system": "سسٹم",
    
    // Dashboard
    "dashboard": "ڈیش بورڈ",
    "download": "ڈاؤن لوڈ",
    "overview": "جائزہ",
    "analytics": "تجزیات",
    "reports": "رپورٹس",
    "notifications": "نوٹیفیکیشنز",
    "total_revenue": "کل آمدنی",
    "subscriptions": "رکنیت",
    "sales": "فروخت",
    "active_now": "فی الوقت فعال",
    "from_last_month": "گزشتہ مہینے سے",
    "since_last_hour": "گزشتہ گھنٹے سے",
    "recent_sales": "حالیہ فروخت",
    "sales_this_month": "آپ نے اس مہینے 265 فروخت کیے ہیں۔",
    "revenue_overview": "آمدنی کا جائزہ",
    "revenue_chart_description": "اپنی آمدنی اور منافع کے رجحانات کو ٹریک کریں",
    "Today": "آج",
    "This Week": "یہ ہفتہ",
    "This Month": "یہ مہینہ",
    "This Year": "یہ سال",
    "Revenue": "آمدنی",
    "Profit": "منافع",
    "Low Stock Alerts": "کم اسٹاک الرٹس",
    "out_of_stock": "اسٹاک ختم",
    "low_stock": "کم اسٹاک",
    "all_products_well_stocked": "تمام مصنوعات اچھی طرح سٹاک میں ہیں!",
    "view_all_products": "تمام مصنوعات دیکھیں",
    "units_sold": "یونٹس فروخت",
    "in_stock": "اسٹاک میں",
    "Top Selling Products": "سب سے زیادہ فروخت ہونے والی مصنوعات",
    "Top Customers": "بہترین گاہک",
    "purchases": "خریداریاں",
    "Recent Activities": "حالیہ سرگرمیاں",
    "Quick Actions": "فوری ایکشنز",
    "Create Invoice": "انوائس بنائیں",
    "Add Purchase": "خریداری شامل کریں",
    "Add Product": "مصنوعات شامل کریں",
    "View Reports": "رپورٹس دیکھیں",
    "Refresh Dashboard": "ڈیش بورڈ ریفریش کریں",
    "Business Overview": "کاروبار کا جائزہ",
    "Total Sales": "کل فروخت",
    "Low Stock Products": "کم اسٹاک مصنوعات",
    "Pending Invoices": "زیر التواء انوائسز",
    "vs_last_month": "گزشتہ مہینے کے مقابلے میں",
    
    // Reports
    "reports_description": "اپنے تمام کاروباری رپورٹس دیکھیں اور تجزیہ کریں",
    "date_range": "تاریخ کی حد",
    "select_date_range_for_reports": "رپورٹس کے لیے تاریخ کی حد منتخب کریں",
    "start_date": "شروع کی تاریخ",
    "end_date": "آخری تاریخ",
    "pick_date": "تاریخ منتخب کریں",
    "refresh": "ریفریش",
    "export": "ایکسپورٹ",
    "today": "آج",
    "last_7_days": "آخری 7 دن",
    "last_30_days": "آخری 30 دن",
    "profit_loss": "منافع اور نقصان",
    "inventory": "انوینٹری",
    "tax": "ٹیکس",
    "sales_trend": "فروخت کا رجحان",
    "daily_sales_and_profit": "روزانہ فروخت اور منافع کا جائزہ",
    "detailed_sales_data": "تفصیلی فروخت ڈیٹا",
    "date": "تاریخ",
    "invoices": "انوائسز",
    "cost": "لاگت",
    "profit": "منافع",
    "margin": "مارجن",
    "total_profit": "کل منافع",
    "total_invoices": "کل انوائسز",
    "avg_invoice_value": "اوسط انوائس ویلیو",
    "total_purchases": "کل خریداریاں",
    "total_paid": "کل ادا شدہ",
    "balance_due": "باقی رقم",
    "purchase_details": "خریداری کی تفصیلات",
    "supplier": "سپلائر",
    "count": "تعداد",
    "amount": "رقم",
    "paid": "ادا شدہ",
    "balance": "بیلنس",
    "total_products": "کل مصنوعات",
    "stock_value": "اسٹاک ویلیو",
    "top_selling_products": "سب سے زیادہ فروخت ہونے والی مصنوعات",
    "product": "مصنوعات",
    "category": "زمرہ",
    "quantity_sold": "فروخت شدہ مقدار",
    "revenue": "آمدنی",
    "current_stock": "موجودہ اسٹاک",
    "unique_customers": "منفرد گاہک",
    "avg_transaction": "اوسط لین دین",
    "top_customers": "بہترین گاہک",
    "customer": "گاہک",
    "phone": "فون",
    "total_spent": "کل خرچ",
    "avg_purchase": "اوسط خریداری",
    "last_purchase": "آخری خریداری",
    "supplier_analysis": "سپلائر کا تجزیہ",
    "total_amount": "کل رقم",
    "total_expenses": "کل اخراجات",
    "expense_count": "اخراجات کی تعداد",
    "avg_expense": "اوسط اخراجات",
    "expense_by_category": "زمرہ کے لحاظ سے اخراجات",
    "revenue_section": "آمدنی سیکشن",
    "cost_of_goods_sold": "فروخت شدہ سامان کی لاگت",
    "gross_profit": "مجموعی منافع",
    "expenses_section": "اخراجات سیکشن",
    "net_profit_loss": "خالص منافع / نقصان",
    "net_profit": "خالص منافع",
    "net_margin": "خالص مارجن",
    "inventory_details": "انوینٹری کی تفصیلات",
    "all_products": "تمام مصنوعات",
    "stock": "اسٹاک",
    "value": "قیمت",
    "status": "حیثیت",
    "total_tax_collected": "کل ٹیکس اکٹھا",
    "monthly_tax_summary": "ماہانہ ٹیکس خلاصہ",
    "month": "مہینہ",
    "tax_collected": "ٹیکس اکٹھا",
    
    // User Profile and Authentication
    "upgrade_to_pro": "پرو ورژن حاصل کریں",
    "account": "اکاؤنٹ",
    "profile": "پروفائل",
    "billing": "بلنگ",
    "settings": "سیٹنگز",
    "new_team": "نئی ٹیم",
    "log_out": "لاگ آؤٹ",
    "logout_success": "کامیابی سے لاگ آؤٹ ہو گیا!",
    
    // Suppliers page
    "suppliers_list": "سپلائرز کی فہرست",
    "manage_suppliers": "اپنے سپلائرز کو یہاں منظم کریں۔",
    "search_suppliers": "سپلائرز تلاش کریں...",
    "add_supplier": "سپلائر شامل کریں",
    "edit_supplier": "سپلائر میں ترمیم کریں",
    "delete_supplier": "سپلائر حذف کریں",
    "supplier_name": "سپلائر کا نام",
    
    // Customers page
    "customers_list": "کسٹمرز کی فہرست",
    "manage_customers": "اپنے کسٹمرز کو یہاں منظم کریں۔",
    "search_customers": "کسٹمرز تلاش کریں...",
    "search_customers_by_name_or_phone": "نام یا فون سے تلاش کریں...",
    "filter_customers": "کسٹمرز فلٹر کریں...",
    "add_customer": "کسٹمر شامل کریں",
    "edit_customer": "کسٹمر میں ترمیم کریں",
    "delete_customer": "کسٹمر حذف کریں",
    "customer_name": "کسٹمر کا نام",
    "enter_customer_name": "کسٹمر کا نام درج کریں",
    "no_customers_found": "کوئی کسٹمر نہیں ملا",
    
    // Products page
    "products_list": "پروڈکٹس کی فہرست",
    "manage_products": "اپنے پروڈکٹس کو یہاں منظم کریں۔",
    "search_products": "پروڈکٹس تلاش کریں...",
    "search_categories": "کیٹگریز تلاش کریں...",
    "filter_products": "پروڈکٹس فلٹر کریں...",
    "add_product": "پروڈکٹ شامل کریں",
    "edit_product": "پروڈکٹ میں ترمیم کریں",
    "delete_product": "پروڈکٹ حذف کریں",
    "product_name": "پروڈکٹ کا نام",
    "description": "تفصیل",
    "barcode": "بارکوڈ",
    "price": "قیمت",
    "stock_quantity": "اسٹاک کی مقدار",
    "qty": "مقدار",
    
    // Product CRUD operations
    "product_created_successfully": "پروڈکٹ کامیابی سے بنایا گیا",
    "product_updated_successfully": "پروڈکٹ کامیابی سے اپ ڈیٹ ہوگیا",
    "product_deleted_successfully": "پروڈکٹ کامیابی سے حذف ہوگیا",
    "update_product_description": "یہاں پروڈکٹ کو اپ ڈیٹ کریں۔ ہو جانے پر محفوظ کریں۔",
    "create_product_description": "یہاں نیا پروڈکٹ بنائیں۔ ہو جانے پر محفوظ کریں۔",
    
    // Delete dialog
    "delete_product_confirmation": "کیا آپ واقعی حذف کرنا چاہتے ہیں",
    "delete_product_warning": "یہ عمل پروڈکٹ کو مستقل طور پر ہٹا دے گا",
    "delete_product_warning_suffix": "سسٹم سے۔ اسے واپس نہیں کیا جا سکتا۔",
    "delete_product_placeholder": "حذف کرنے کی تصدیق کے لیے پروڈکٹ داخل کریں۔",
    "delete_operation_warning": "براہ کرم محتاط رہیں، اس آپریشن کو واپس نہیں کیا جا سکتا۔",
    
    // Bulk Edit Products
    "bulk_edit_products": "بلک ایڈٹ پروڈکٹس",
    "bulk_edit_selected": "منتخب کردہ بلک ایڈٹ",
    "edit_selected_products": "{count} منتخب شدہ پروڈکٹس ایڈٹ کریں",
    "enter_new_price": "نئی قیمت داخل کریں (موجودہ رکھنے کے لیے خالی چھوڑیں)",
    "enter_new_cost": "نئی لاگت داخل کریں (موجودہ رکھنے کے لیے خالی چھوڑیں)",
    "enter_new_quantity": "نئی مقدار داخل کریں (موجودہ رکھنے کے لیے خالی چھوڑیں)",
    "update_products": "پروڈکٹس اپ ڈیٹ کریں",
    "bulk_update_success": "کامیابی سے {count} پروڈکٹس اپ ڈیٹ کیے گئے",
    "no_products_selected": "کوئی پروڈکٹ منتخب نہیں",
    "select_products_first": "پہلے پروڈکٹس منتخب کریں",
    "enter_at_least_one_value": "اپ ڈیٹ کرنے کے لیے کم از کم ایک قیمت داخل کریں",
    "no_changes_to_update": "اپ ڈیٹ کرنے کے لیے کوئی تبدیلی نہیں",
    "enter_new": "نئی داخل کریں",
    "current": "موجودہ",
    // "bulk_update_success": "پروڈکٹس کامیابی سے اپ ڈیٹ ہوگئے!",
    
    // Low Stock Alert System
    "low_stock_alert": "کم اسٹاک الرٹ",
    "low_stock_alerts_disabled": "کم اسٹاک الرٹس غیر فعال ہیں",
    "enable_alerts": "الرٹس فعال کریں",
    // "all_products_well_stocked": "تمام پروڈکٹس اچھی طرح اسٹاک میں ہیں",
    "products_need_attention": "کچھ پروڈکٹس پر توجہ درکار ہے",
    // "out_of_stock": "اسٹاک ختم",
    "critical_stock": "نازک اسٹاک",
    // "low_stock": "کم اسٹاک",
    "critical": "نازک",
    "out_of_stock_products": "اسٹاک ختم پروڈکٹس",
    "critical_stock_products": "نازک اسٹاک پروڈکٹس",
    "low_stock_products": "کم اسٹاک پروڈکٹس",
    "and": "اور",
    "more": "مزید",
    "left": "باقی",
    "less_than": "سے کم",
    "units": "یونٹس",
    "showing": "دکھا رہے ہیں",
    "products": "پروڈکٹس",
    "low_stock_alert_settings": "کم اسٹاک الرٹ سیٹنگز",
    "configure_low_stock_threshold": "کم اسٹاک وارننگ کب دکھانی ہے ترتیب دیں",
    "low_stock_threshold": "کم اسٹاک کی حد",
    "alert_when_stock_below_threshold": "جب پروڈکٹ اسٹاک اس نمبر سے نیچے گرے تو الرٹ کریں",
    "enable_notifications": "اطلاعات فعال کریں",
    "enabled": "فعال",
    "disabled": "غیر فعال",
    "save_settings": "سیٹنگز محفوظ کریں",
    "products_need_immediate_restock": "پروڈکٹس کو فوری طور پر دوبارہ اسٹاک کرنے کی ضرورت ہے",
    "less_than_x_units": "{count} یونٹس سے کم",
    "below_threshold": "حد سے نیچے",
    "products_requiring_restock": "دوبارہ اسٹاک کی ضرورت والے پروڈکٹس",
    "search_by_name_or_barcode": "نام یا بارکوڈ سے تلاش کریں",
    "filter_by_status": "حیثیت سے فلٹر کریں",
    "all": "تمام",
    "no_low_stock_products": "کوئی کم اسٹاک پروڈکٹس نہیں",
    "showing_x_products": "{count} پروڈکٹس دکھا رہے ہیں",
    "export_csv": "CSV ایکسپورٹ کریں",
    "back": "واپس",
    "no_items": "کوئی آئٹمز نہیں",
    
    // Barcode functionality
    "scan_barcode": "بارکوڈ اسکین کریں",
    "enter_barcode": "بارکوڈ داخل کریں",
    "barcode_scanner": "بارکوڈ اسکینر",
    "barcode_input": "بارکوڈ انپٹ",
    "barcode_scanned": "بارکوڈ اسکین ہوگیا",
    "barcode_entered": "بارکوڈ داخل کیا گیا",
    "enter_or_scan_barcode": "بارکوڈ داخل کریں یا اسکین کریں...",
    "point_camera_at_barcode": "بارکوڈ اسکین کرنے کے لیے کیمرہ اس طرف کریں",
    "camera_access_failed": "کیمرہ تک رسائی ناکام۔ براہ کرم اجازات چیک کریں۔",
    "try_again": "دوبارہ کوشش کریں",
    "cancel": "منسوخ کریں",
    "add": "شامل کریں",
    "use_scanner_gun": "اسکینر گن استعمال کریں",
    "stop_scanner": "اسکینر بند کریں",
    "scanner_ready": "اسکینر تیار ہے - بارکوڈ اسکین کریں",
    "scanner_listening": "بارکوڈ اسکینر کی سن رہا ہے...",
    "scanner_instructions": "اپنا بارکوڈ گن استعمال کریں یا ہاتھ سے ٹائپ کریں",
    "barcode_product_search": "بارکوڈ پروڈکٹ تلاش",
    "enter_barcode_to_search": "تلاش کے لیے بارکوڈ داخل کریں...",
    "product_found": "پروڈکٹ مل گیا",
    "product_not_found": "پروڈکٹ نہیں ملا",
    
    // Invoice functionality
    "create_invoice": "انوائس بنائیں",
    "create_new_invoice": "نئی انوائس بنائیں",
    "invoice_details": "انوائس کی تفصیلات",
    "invoice_items": "انوائس آئٹمز",
    "add_item": "آئٹم شامل کریں",
    "select_product": "پروڈکٹ منتخب کریں",
    "select_product_for_manual_entries": "محفوظ کرنے سے پہلے تمام دستی اندراجات کے لیے پروڈکٹ منتخب کریں",
    "product_catalog": "پروڈکٹ کیٹالاگ",
    "invoice_type": "انوائس کی قسم",
    "select_customer": "کسٹمر منتخب کریں",
    "walk_in_customer": "واک ان کسٹمر",
    "cash": "نقد",
    "credit": "ادھار",
    "pending": "زیر التواء",
    "due_date": "آخری تاریخ",
    "no_items_added": "انوائس میں ابھی تک کوئی آئٹم شامل نہیں",
    "subtotal": "ذیلی مجموعہ",
    "discount": "رعایت",
    "tax_rate": "ٹیکس کی شرح",
    "total": "کل",
    "type": "قسم",
    "paid_amount": "ادا شدہ رقم",
    "notes": "نوٹس",
    "add_notes": "نوٹس یا تبصرے شامل کریں...",
    "save_invoice": "انوائس محفوظ کریں",
    "update_invoice": "انوائس اپڈیٹ کریں",
    "save_and_print": "محفوظ کریں اور پرنٹ کریں",
    "save_and_print_receipt": "محفوظ کریں اور رسید پرنٹ کریں",
    "save_and_print_a4": "A4 محفوظ کریں اور پرنٹ کریں",
    "update_and_print_receipt": "اپڈیٹ کریں اور رسید پرنٹ کریں",
    "update_and_print_a4": "اپڈیٹ کریں اور A4 پرنٹ کریں",
    "print_success": "انوائس پرنٹر کو بھیج دی گئی",
    "print_error": "انوائس پرنٹ کرنے میں ناکام",
    "saving": "محفوظ کر رہا ہے",
    
    // Print Template Translations
    "print_business_name": "آپ کے کاروبار کا نام",
    "print_business_address": "123 کاروباری سٹریٹ، شہر، ریاست 12345",
    "print_business_phone": "فون: (555) 123-4567",
    "print_business_email": "ای میل: info@business.com",
    "print_tax_id": "ٹیکس آئی ڈی: 123-456-789",
    "print_invoice_title": "انوائس",
    "print_time": "وقت",
    "print_bill_to": "بل برائے:",
    "print_invoice_details": "انوائس کی تفصیلات",
    "print_issue_date": "تاریخ",
    "print_items_count": "اشیاء کی تعداد",
    "print_items_purchased": "خریدی گئی اشیاء",
    "print_product_name": "پروڈکٹ کا نام",
    "print_unit_price": "یونٹ قیمت",
    "print_quantity": "مقدار",
    "print_paid_in_full": "مکمل ادا شدہ",
    "print_balance_due": "باقی رقم",
    "print_paid": "ادا شدہ",
    "print_invoice_barcode": "انوائس بارکوڈ",
    "print_scan_to_verify": "انوائس تصدیق کے لیے اسکین کریں",
    "print_additional_notes": "اضافی نوٹس",
    "print_thank_you_message": "آپ کے کاروبار کے لیے شکریہ!",
    "print_keep_receipt": "براہ کرم اپنے ریکارڈ کے لیے یہ رسید محفوظ رکھیں",
    "print_visit_again": "جلد ہی دوبارہ آئیں",
    "print_receipt_btn": "رسید پرنٹ کریں",
    "print_invoice_btn": "انوائس پرنٹ کریں",
    "print_close": "بند کریں",
    "print_options": "پرنٹ کے اختیارات",
    "print_payment_information": "ادائیگی کی معلومات",
    "print_payment_status": "ادائیگی کی حالت",
    "print_completed": "مکمل",
    "print_pending_payment": "زیر التواء ادائیگی",
    "print_powered_by": "لوجکس پلس سافٹ ویِر سولیوشنز 03211626195",
    "print_delivery_charge": "ڈیلیوری چارج",
    "print_service_charge": "سروس چارج",
    "print_amount_paid": "ادا شدہ رقم",
    "print_generated_on": "تیار شدہ",
    
    // Barcode
    "generate": "بنائیں",
    "barcode_generated": "بارکوڈ کامیابی سے بنا دیا گیا",
    
    // Payment Receipt
    "Payment Receipt": "ادائیگی کی رسید",
    "Generate Receipt": "رسید بنائیں",
    "Print Receipt": "رسید پرنٹ کریں",
    "Receipt No": "رسید نمبر",
    "Received From": "وصول کنندہ",
    "Payment Date": "ادائیگی کی تاریخ",
    "Previous Balance": "سابقہ بیلنس",
    "Payment Received": "ادائیگی موصول",
    "Remaining Balance": "بقایا رقم",
    "Received By": "وصول کنندہ",
    "Customer Signature": "کسٹمر کے دستخط",
    "This is a computer generated receipt": "یہ کمپیوٹر سے تیار شدہ رسید ہے",
    "Thank you for your payment": "آپ کی ادائیگی کا شکریہ",
    
    // Product History
    "product_price_history": "پروڈکٹ کی قیمت کی تاریخ",
    "loading_history": "تاریخ لوڈ ہو رہی ہے...",
    "error_loading_history": "تاریخ لوڈ کرنے میں خرابی",
    "no_purchase_history": "خریداری کی تاریخ نہیں ملی",
    "this_is_first_purchase": "یہ اس کسٹمر کے لیے اس پروڈکٹ کی پہلی خریداری ہے",
    "last_price": "آخری قیمت",
    "current_price": "موجودہ قیمت",
    "total_quantity": "کل مقدار",
    "same_price": "وہی قیمت",
    "increase": "اضافہ",
    "decrease": "کمی",
    "compared_to_last_purchase": "آخری خریداری سے موازنہ",
    "purchase_history": "خریداری کی تاریخ",
    "latest": "تازہ ترین",
    "than_previous": "پچھلے سے",
    // "more": "زیادہ",
    "less": "کم",
    "average_price": "اوسط قیمت",
    "min_price": "کم سے کم قیمت",
    "max_price": "زیادہ سے زیادہ قیمت",
    "view_history": "تاریخ دیکھیں",

    // Pending Invoice Converter
    "convert_pending_invoices": "زیر التواء انوائسز کو تبدیل کریں",
    "select_pending_invoices_to_convert_to_credit": "کریڈٹ میں تبدیل کرنے کے لیے زیر التواء انوائسز منتخب کریں",
    "please_select_customer_and_invoices": "برائے کرم کسٹمر اور کم از کم ایک انوائس منتخب کریں",
    "no_items_to_convert": "تبدیل کرنے کے لیے کوئی آئٹم نہیں",
    "credit_invoice_created_successfully": "کریڈٹ انوائس کامیابی سے بنائی گئی",
    "failed_to_create_invoice": "انوائس بنانے میں ناکامی",
    "no_pending_invoices_found": "اس کسٹمر کے لیے کوئی زیر التواء انوائس نہیں ملی",
    "loading_invoices": "انوائسز لوڈ ہو رہے ہیں...",
    "pending_invoices": "زیر التواء انوائسز",
    "select_all": "تمام منتخب کریں",
    "deselect_all": "تمام غیر منتخب کریں",
    "merged_items": "ملائے گئے آئٹمز",
    "from": "سے",
    "items": "آئٹمز",
    // "due_date": "واجب الادا تاریخ",
    "invoice_date": "انوائس کی تاریخ",
    "enter_notes": "نوٹس درج کریں (اختیاری)",
    "create_and_print_receipt": "بنائیں اور رسید پرنٹ کریں",
    "create_and_print_a4": "بنائیں اور A4 پرنٹ کریں",
    "create_without_printing": "بغیر پرنٹ کے بنائیں",
    "creating": "بن رہا ہے...",
    "print_failed": "پرنٹ ناکام",
    
    // Enhanced Pending Invoice Converter
    "pending_only": "صرف زیر التواء",
    "converted_only": "صرف تبدیل شدہ", 
    "all_invoices": "تمام انوائسز",
    "converted_invoices": "تبدیل شدہ انوائسز",
    "no_converted_invoices_found": "کوئی تبدیل شدہ انوائس نہیں ملی",
    "converted": "تبدیل شدہ",
    "converted_on": "پر تبدیل کیا گیا",
    "converted_pending": "تبدیل شدہ زیر التواء",
    
    // Invoice List
    "invoice_management": "انوائس منیجمنٹ",
    "manage_customer_invoices": "کسٹمر انوائسز اور ادائیگیوں کا انتظام",
    // "loading_invoices": "انوائسز لوڈ ہو رہے ہیں...",
    "error_loading_invoices": "انوائسز لوڈ کرنے میں خرابی",
    "unknown_error": "نامعلوم خرابی",
    "invoice_number": "انوائس #",
    "bill_number": "بل #",
    "invoices_count": "تعداد",
    "all_statuses": "تمام حالات",
    "all_types": "تمام اقسام",
    "draft": "مسودہ",
    "finalized": "حتمی",
    "cancelled": "منسوخ",
    "refunded": "واپس",
    "clear_filters": "فلٹرز صاف کریں",
    "invoices_list": "انوائسز کی فہرست",
    "search_invoices_placeholder": "انوائس #، فون #، کسٹمر...",
    "show": "دکھائیں",
    "return_items": "آئٹمز واپس کریں",
    "no_invoices_found": "کوئی انوائس نہیں ملی",
    "customer_id": "کسٹمر آئی ڈی",
    // "showing": "دکھا رہے ہیں",
    "previous": "پچھلا",
    "next": "اگلا",
    "first": "پہلا",
    "last": "آخری",
    "unknown_customer": "نامعلوم کسٹمر",
    "unit_price": "یونٹ قیمت",
    
    "loading_products": "پروڈکٹس لوڈ ہو رہے ہیں...",
    "with_images": "تصاویر کے ساتھ",
    "without_images": "تصاویر کے بغیر",
    "scan_or_enter_barcode": "بارکوڈ اسکین یا داخل کریں...",
    "barcode_mode_active": "بارکوڈ موڈ فعال",
    
    // Pending Invoice Converter
    // "pending_invoices": "زیرالتواء انوائسز",
    "convert_to_credit": "کریڈٹ میں تبدیل کریں",
    "pending_invoice_converter": "زیرالتواء انوائس کنورٹر",
    // "all_invoices": "تمام انوائسز",
    // "pending_only": "صرف زیرالتواء",
    // "converted_only": "صرف تبدیل شدہ",
    "select_view_mode": "ویو موڈ منتخب کریں",
    "filter_by_date_range": "تاریخ کی رینج سے فلٹر کریں",
    "new_credit_invoice_date": "نئی کریڈٹ انوائس کی تاریخ",
    "new_credit_invoice_due_date": "نئی کریڈٹ انوائس کی آخری تاریخ",
    "new_credit_invoice_details": "نئی کریڈٹ انوائس کی تفصیلات",
    "converted_to_credit": "کریڈٹ میں تبدیل شدہ",
    // "pending": "زیرالتواء",
    "print_invoice": "انوائس پرنٹ کریں",
    "press_enter_to_search": "تلاش کے لیے انٹر دبائیں",
    "no_products_found": "کوئی پروڈکٹ نہیں ملا",
    "no_products_available": "کوئی پروڈکٹ دستیاب نہیں",
    // "low_stock": "کم اسٹاک",
    // "out_of_stock": "اسٹاک ختم",
    "no_product_with_barcode": "اس بارکوڈ کے ساتھ کوئی پروڈکٹ نہیں ملا",
    "consider_adding_new_product": "اسے نیا پروڈکٹ شامل کرنے پر غور کریں",
    "search_error": "تلاش میں خرابی ہوئی",
    "capture_barcode": "بارکوڈ کیپچر کریں",
    "enter_barcode_manually": "بارکوڈ دستی طور پر داخل کریں",
    "barcode_from_image": "تصویر سے بارکوڈ",
    "scanned": "اسکین ہوگیا",
    "click_scanner_button_to_activate": "فعال کرنے کے لیے اسکینر بٹن پر کلک کریں",
    "clear": "صاف کریں",
    
    // Mobile camera scanner  
    "mobile_camera_scanner": "موبائل کیمرہ اسکینر",
    "scanning_for_barcode": "بارکوڈ اسکین کر رہا ہے",
    "enter_barcode_manually_for_testing": "ٹیسٹنگ کے لیے بارکوڈ دستی طور پر داخل کریں",
    "enter_manually_instead": "اس کے بجائے دستی طور پر داخل کریں",
    "scanning_instructions": "اسکیننگ کی ہدایات",
    "hold_phone_steady": "فون کو مستحکم رکھیں",
    "ensure_good_lighting": "اچھی روشنی کو یقینی بنائیں",
    "barcode_should_fill_frame": "بارکوڈ فریم کو بھرنا چاہیے",
    "enter_manually": "دستی طور پر داخل کریں",
    
    // New mobile scanner translations
    "point_camera_at_qr_or_barcode": "کیمرہ کو QR کوڈ یا بارکوڈ پر لگائیں",
    "ensure_good_lighting_or_use_flashlight": "اچھی روشنی یا ٹارچ بٹن استعمال کریں",
    "align_code_within_frame": "کوڈ کو اسکیننگ فریم کے اندر لائیں",
    "detection_is_automatic": "شناخت خودکار ہے - کیپچر دبانے کی ضرورت نہیں",
    "supports_multiple_formats": "QR کوڈز، EAN، Code128 اور مزید کو سپورٹ کرتا ہے",
    "flashlight_turned_off": "ٹارچ بند کر دیا گیا",
    "flashlight_turned_on": "ٹارچ چالو کر دیا گیا",
    "flashlight_not_available": "اس ڈیوائس پر ٹارچ دستیاب نہیں",
    "turn_off_flashlight": "ٹارچ بند کریں",
    "turn_on_flashlight": "ٹارچ چالو کریں",
    "make_sure_to": "یقینی بنائیں کہ",
    "allow_camera_permission": "کیمرہ کی اجازت دیں جب پوچھا جائے",
    "try_refreshing_page": "صفحہ ریفریش کرنے کی کوشش کریں",
    "check_camera_not_used_by_other_app": "چیک کریں کہ کیمرہ کسی اور ایپ میں استعمال تو نہیں ہو رہا",
    "initializing_scanner": "اسکینر شروع کر رہا ہے...",
    "this_will_take_moment": "اس میں صرف ایک لمحہ لگے گا",
    
    // Excel Import functionality
    "import_excel": "ایکسل امپورٹ کریں",
    "import_products_from_excel": "ایکسل سے پروڈکٹس امپورٹ کریں",
    "upload_excel_file_to_import_products": "پروڈکٹس کو بلک امپورٹ کرنے کے لیے ایکسل فائل اپ لوڈ کریں",
    "download_template_first": "مطلوبہ فارمیٹ دیکھنے کے لیے پہلے ٹیمپلیٹ ڈاؤن لوڈ کریں",
    "download_template": "ٹیمپلیٹ ڈاؤن لوڈ کریں",
    "select_excel_file": "ایکسل فائل منتخب کریں",
    "selected_file": "منتخب شدہ فائل",
    "parse_and_validate": "پارس اور توثیق کریں",
    "parsing": "پارس کر رہا ہے",
    "validation_errors": "توثیق کی خرابیاں",
    "found_in_excel_file": "ایکسل فائل میں ملی",
    "row": "قطار",
    "field": "فیلڈ",
    "error": "خرابی",
    "file_parsed_successfully": "فائل کامیابی سے پارس ہوگئی",
    "products_ready_to_import": "پروڈکٹس امپورٹ کے لیے تیار",
    "preview_first_products": "پیش نظارہ (پہلے 5 پروڈکٹس)",
    "import_successful": "امپورٹ کامیاب",
    "products_imported": "پروڈکٹس امپورٹ ہوگئے",
    "no_products_to_import": "امپورٹ کرنے کے لیے کوئی پروڈکٹ نہیں",
    "error_importing_products": "پروڈکٹس امپورٹ کرنے میں خرابی",
    "please_select_file": "براہ کرم فائل منتخب کریں",
    "invalid_file_type": "غلط فائل قسم۔ براہ کرم .xlsx، .xls، یا .csv فائل منتخب کریں",
    "file_is_empty": "فائل خالی ہے",
    "error_parsing_file": "فائل پارس کرنے میں خرابی",
    "template_downloaded": "ٹیمپلیٹ کامیابی سے ڈاؤن لوڈ ہوگیا",
    "warning_existing_products": "انتباہ: امپورٹ سے نئے پروڈکٹس شامل ہوں گے۔ ایک ہی بارکوڈ والے موجودہ پروڈکٹس متاثر نہیں ہوں گے۔",
    "importing": "امپورٹ کر رہا ہے",
    "import": "امپورٹ",
    "product_name_required": "پروڈکٹ کا نام ضروری ہے",
    "price_required": "قیمت ضروری ہے",
    "price_must_be_positive": "قیمت ایک درست مثبت نمبر ہونا چاہیے",
    "cost_required": "لاگت ضروری ہے",
    "cost_must_be_positive": "لاگت ایک درست مثبت نمبر ہونا چاہیے",
    "stock_quantity_required": "اسٹاک کی مقدار ضروری ہے",
    "stock_must_be_positive": "اسٹاک کی مقدار ایک درست مثبت نمبر ہونا چاہیے",
    "low_stock_must_be_positive": "کم اسٹاک کی حد ایک درست مثبت نمبر ہونا چاہیے",
    "ready_to_import": "امپورٹ کے لیے تیار",
    
    // Customer import functionality
    "import_customers_from_excel": "ایکسل سے کسٹمرز امپورٹ کریں",
    "upload_excel_file_to_import_customers": "کسٹمرز کو بلک امپورٹ کرنے کے لیے ایکسل فائل اپ لوڈ کریں",
    "no_customers_to_import": "امپورٹ کرنے کے لیے کوئی کسٹمر نہیں",
    "error_importing_customers": "کسٹمرز امپورٹ کرنے میں خرابی",
    "customer_name_required": "کسٹمر کا نام ضروری ہے",
    "invalid_email_format": "ای میل فارمیٹ غلط ہے",
    "balance_must_be_number": "بیلنس ایک درست نمبر ہونا چاہیے",
    "warning_importing_customers": "انتباہ: امپورٹ سے آپ کے ڈیٹا بیس میں نئے کسٹمرز شامل ہوں گے۔",
    
    // Supplier import functionality
    "import_suppliers_from_excel": "ایکسل سے سپلائرز امپورٹ کریں",
    "upload_excel_file_to_import_suppliers": "سپلائرز کو بلک امپورٹ کرنے کے لیے ایکسل فائل اپ لوڈ کریں",
    "no_suppliers_to_import": "امپورٹ کرنے کے لیے کوئی سپلائر نہیں",
    "error_importing_suppliers": "سپلائرز امپورٹ کرنے میں خرابی",
    "supplier_name_required": "سپلائر کا نام ضروری ہے",
    "warning_importing_suppliers": "انتباہ: امپورٹ سے آپ کے ڈیٹا بیس میں نئے سپلائرز شامل ہوں گے۔",
    "suppliers_plural": "سپلائرز",
    "importing_suppliers": "سپلائرز امپورٹ کر رہا ہے...",
    
    // Barcode demo page
    "barcode_inventory_system": "بارکوڈ انوینٹری سسٹم",
    "barcode_scanning_options": "بارکوڈ اسکیننگ آپشنز",
    "hardware_scanner": "ہارڈویئر اسکینر",
    "use_dedicated_scanner_gun": "مخصوص بارکوڈ اسکینر گن استعمال کریں",
    "scan_with_barcode_gun": "بارکوڈ گن سے اسکین کریں...",
    "camera_scanner": "کیمرہ اسکینر",
    "use_device_camera": "اسکین کے لیے اپنا ڈیوائس کیمرہ استعمال کریں",
    "scan_with_camera": "کیمرے سے اسکین کریں",
    "scanned_products": "اسکین شدہ پروڈکٹس",
    "no_products_scanned_yet": "ابھی تک کوئی پروڈکٹ اسکین نہیں ہوا",
    "scan_barcode_to_add_products": "پروڈکٹ شامل کرنے کے لیے بارکوڈ اسکین کریں",
    "each": "ہر ایک",
    "total_value": "کل قیمت",
    "last_scanned_barcode": "آخری اسکین شدہ بارکوڈ",
    "implementation_guide": "نافذ کرنے کا گائیڈ",
    "hardware_solution": "ہارڈویئر حل",
    "camera_solution": "کیمرہ حل",
    "manual_entry": "دستی انٹری",
    
    // Image upload functionality
    "product_image": "پروڈکٹ کی تصویر",
    "upload_image": "تصویر اپ لوڈ کریں",
    "remove_image": "تصویر ہٹائیں",
    "drag_drop_image": "یہاں تصویر کو گھسیٹ کر چھوڑیں",
    "or_click_to_select": "یا منتخب کرنے کے لیے کلک کریں",
    "or_use_options_below": "یا نیچے دیے گئے اختیارات استعمال کریں",
    "drop_image_here": "تصویر یہاں چھوڑیں",
    "uploading_image": "تصویر اپ لوڈ ہو رہی ہے...",
    "image_upload_failed": "تصویر اپ لوڈ ناکام",
    "image_uploaded_successfully": "تصویر کامیابی سے اپ لوڈ ہوئی",
    "image_removed_successfully": "تصویر کامیابی سے ہٹا دی گئی",
    "image_load_failed": "تصویر لوڈ کرنے میں ناکام",
    "select_file": "فائل منتخب کریں",
    "take_photo": "تصویر لیں",
    "capture": "کیپچر",
    "switch_camera": "کیمرہ تبدیل کریں",
    "retry": "دوبارہ کوشش",
    
    // Common fields
    "email": "ای میل",
    "whatsapp": "واٹس ایپ",
    "address": "پتہ",
    "actions": "کارروائیاں",
    "no_results": "کوئی نتائج نہیں۔",
    "name_required": "نام درکار ہے۔",
    
    // Table actions
    "edit": "ترمیم کریں",
    "delete": "حذف کریں",
    "asc": "چڑھتا ہوا",
    "desc": "اترتا ہوا",
    "hide": "چھپائیں",
    "view": "دیکھیں",
    "toggle_columns": "کالم دکھائیں/چھپائیں",
    "select": "منتخب کریں",
    
    // Pagination
    "rows_per_page": "صفحہ کے لائنوں کی تعداد",
    "page": "صفحہ",
    "of": "کُل",
    "to": "سے",
    "row_selected": "قطاریں منتخب کی گئیں۔",
    "Showing": "دکھا رہا ہے",
    "First": "پہلا",
    "Last": "آخری",
    "Previous": "پچھلا",
    "Next": "اگلا",
    "Records per page": "فی صفحہ ریکارڈز",
    "Show": "دکھائیں",
    "suppliers": "سپلائرز",
    "entries": "اندراجات",
    "expenses": "اخراجات",
    "Export to Excel": "ایکسل میں ایکسپورٹ کریں",
    "Data exported successfully": "ڈیٹا کامیابی سے ایکسپورٹ ہوا",
    "Failed to export data": "ڈیٹا ایکسپورٹ ناکام",
    
    // Dialog content
    "update_supplier": "یہاں سپلائر کو اپ ڈیٹ کریں۔",
    "create_supplier": "یہاں نیا سپلائر بنائیں۔",
    "update_customer": "یہاں کسٹمر کو اپ ڈیٹ کریں۔",
    "create_customer": "یہاں نیا کسٹمر بنائیں۔",
    "click_save": "جب آپ مکمل کر لیں تو محفوظ کریں پر کلک کریں۔",
    "save_changes": "تبدیلیاں محفوظ کریں",
    "delete_confirmation": "کیا آپ واقعی حذف کرنا چاہتے ہیں",
    "delete_warning": "یہ عمل سپلائر کو مستقل طور پر سسٹم سے ہٹا دے گا",
    "delete_customer_warning": "یہ عمل کسٹمر کو مستقل طور پر سسٹم سے ہٹا دے گا",
    "from_system": "اسے واپس نہیں کیا جا سکتا۔",
    "enter_name_confirm": "حذف کرنے کی تصدیق کے لیے سپلائر کا نام درج کریں۔",
    "enter_customer_name_confirm": "حذف کرنے کی تصدیق کے لیے کسٹمر کا نام درج کریں۔",
    "warning": "انتباہ!",
    "operation_warning": "براہ کرم محتاط رہیں، اس آپریشن کو واپس نہیں کیا جا سکتا۔",
    
    // Common UI components
    "loading": "لوڈ ہو رہا ہے...",
    
    // Success Messages
    "supplier_created_success": "سپلائر کامیابی سے بنایا گیا",
    "supplier_updated_success": "سپلائر کامیابی سے اپڈیٹ ہو گیا",
    "supplier_deleted_success": "سپلائر کامیابی سے حذف کر دیا گیا",
    "customer_created_success": "کسٹمر کامیابی سے بنایا گیا",
    "customer_updated_success": "کسٹمر کامیابی سے اپڈیٹ ہو گیا",
    "customer_deleted_success": "کسٹمر کامیابی سے حذف کر دیا گیا",
    
    // Sidebar Navigation
    "general": "عمومی",
    // "dashboard": "ڈیش بورڈ",
    "customers": "کسٹمرز",
    "categories": "کیٹگریز",
    // "products": "پروڈکٹس",
    "purchase": "خریداری",
    // "invoices": "انوائسز",
    "returns": "واپسیاں",
    
    // Returns Management
    "returns_management": "واپسیوں کا انتظام",
    "manage_returns": "کسٹمر واپسیاں اور رقم کی واپسی کا انتظام کریں",
    "create_return": "واپسی بنائیں",
    "new_return_request": "نئی واپسی کی درخواست بنائیں",
    "returns_list": "واپسیوں کی فہرست",
    "no_returns_found": "کوئی واپسی نہیں ملی",
    "return_number": "واپسی نمبر",
    "original_invoice": "اصل انوائس",
    "original_invoice_information": "اصل انوائس کی معلومات",
    "invoice_details_prefilled": "انوائس کی تفصیلات پہلے سے بھری ہیں اور تبدیل نہیں کی جا سکتیں",
    "return_date": "واپسی کی تاریخ",
    "return_type": "واپسی کی قسم",
    "return_status": "واپسی کی حالت",
    "return_reason": "واپسی کی وجہ",
    "refund_amount": "واپسی کی رقم",
    "total_return_amount": "کل واپسی کی رقم",
    "restocking_fee": "دوبارہ اسٹاک کرنے کی فیس",
    "processing_fee": "پروسیسنگ فیس",
    "receipt_required": "رسید ضروری",
    "receipt_provided": "رسید فراہم کی گئی",
    "refund_method": "رقم واپسی کا طریقہ",
    "return_condition": "حالت",
    "restockable": "دوبارہ اسٹاک کے قابل",
    "returned_quantity": "واپس شدہ مقدار",
    "return_amount": "واپسی کی رقم",
    "rejection_reason": "مسترد کرنے کی وجہ",
    
    // Return Types
    "full_refund": "مکمل واپسی",
    "partial_refund": "جزوی واپسی",
    "exchange": "تبادلہ",
    "store_credit": "اسٹور کریڈٹ",
    
    // Return Status
    "return_pending": "زیر التواء",
    "return_approved": "منظور شدہ",
    "return_rejected": "مسترد شدہ",
    "return_processed": "کارروائی مکمل",
    "return_completed": "مکمل",
    
    // Refund Methods
    "refund_cash": "نقد",
    "refund_card": "کارڈ",
    "original_payment": "اصل ادائیگی",
    
    // Item Conditions
    "condition_new": "نیا",
    "condition_used": "استعمال شدہ",
    "condition_damaged": "خراب",
    "condition_defective": "خرابی والا",
    
    // Return Reasons
    "reason_defective": "خرابی والا",
    "wrong_item": "غلط آئٹم",
    "customer_request": "کسٹمر کی درخواست",
    "reason_damaged": "نقصان",
    "reason_expired": "ختم ہو گیا",
    "reason_other": "دیگر",
    "select_reason": "وجہ منتخب کریں",
    "select_condition": "حالت منتخب کریں",
    "reason": "وجہ",
    "condition": "حالت",
    
    // Return Actions
    "approve_return": "واپسی منظور کریں",
    "reject_return": "واپسی مسترد کریں",
    "process_return": "واپسی پر کارروائی کریں",
    "view_details": "تفصیلات دیکھیں",
    "add_return_item": "واپسی آئٹم شامل کریں",
    "remove_item": "آئٹم ہٹائیں",
    "search_invoice": "انوائس تلاش کریں",
    "select_invoice": "انوائس منتخب کریں",
    "return_invoice_items": "انوائس آئٹمز",
    "return_details": "واپسی کی تفصیلات",
    "financial_summary": "مالی خلاصہ",
    "return_created_successfully": "واپسی کامیابی سے بنائی گئی",
    "return_approved_successfully": "واپسی کامیابی سے منظور ہوئی",
    "fees_and_summary": "فیسیں اور خلاصہ",
    "original_qty": "اصل مقدار",
    "return_qty": "واپسی مقدار", 
    // "return_items": "واپسی آئٹمز",
    "items_from_invoice": "انوائس سے آئٹمز",
    "restock": "دوبارہ اسٹاک",
    "creating_return": "واپسی بنائی جا رہی ہے",
    "final_refund_amount": "حتمی رقم واپسی",
    "fees_exceed_return_amount": "فیسیں واپسی کی رقم سے زیادہ ہیں",
    "customer_may_owe_money": "کسٹمر کو پیسے ادا کرنے پڑ سکتے ہیں",
    "no_items_selected_for_return": "واپسی کے لیے کوئی آئٹم منتخب نہیں",
    "add_your_first_item": "اپنا پہلا آئٹم شامل کریں",
    "enter_return_reason": "واپسی کی وجہ درج کریں...",
    "enter_additional_notes": "اضافی نوٹس درج کریں...",
    "enter_rejection_reason": "مسترد کرنے کی وجہ درج کریں...",
    "select_return_type": "واپسی کی قسم منتخب کریں",
    "select_refund_method": "رقم واپسی کا طریقہ منتخب کریں",
    "skip_invoice_selection": "انوائس کا انتخاب چھوڑیں",
    "enter_invoice_number": "انوائس نمبر درج کریں",
    "search_by_invoice_or_customer": "انوائس نمبر یا کسٹمر کے نام سے تلاش کریں...",
    "return_rejected_successfully": "واپسی کامیابی سے مسترد ہوئی",
    "return_processed_successfully": "واپسی پر کامیابی سے کارروائی ہوئی",
    // "enter_return_reason": "براہ کرم واپسی کی وجہ درج کریں",
    "add_items_to_return": "براہ کرم واپسی کے لیے آئٹمز شامل کریں",
    
    // Roles & Permissions
    "roles_permissions": "رولز اور اجازتیں",
    "administration": "انتظامیہ",
    "roles_management": "رولز کا انتظام",
    "roles_management_description": "صارف کے رولز اور اجازتوں کا انتظام کریں",
    "create_role": "رول بنائیں",
    "edit_role": "رول میں ترمیم کریں",
    "delete_role": "رول حذف کریں",
    "role_name": "رول کا نام",
    "role_description": "رول کی تفصیل",
    "permissions": "اجازتیں",
    "manage_permissions": "اجازتوں کا انتظام کریں",
    "all_roles": "تمام رولز",
    "roles_list_description": "تمام سسٹم رولز دیکھیں اور ان کا انتظام کریں",
    "no_roles_found": "کوئی رول نہیں ملا",
    "role_created_successfully": "رول کامیابی سے بنایا گیا",
    "role_updated_successfully": "رول کامیابی سے اپ ڈیٹ ہو گیا",
    "role_deleted_successfully": "رول کامیابی سے حذف ہو گیا",
    "permissions_updated_successfully": "اجازتیں کامیابی سے اپ ڈیٹ ہو گئیں",
    "system_role": "سسٹم رول",
    "custom_role": "کسٹم رول",
    "active": "فعال",
    "inactive": "غیر فعال",
    "enter_role_name": "رول کا نام درج کریں",
    "enter_role_description": "رول کی تفصیل درج کریں (اختیاری)",
    "system_roles_cannot_be_deleted": "سسٹم رولز حذف نہیں کیے جا سکتے",
    "system_roles_cannot_be_modified": "سسٹم رولز میں ترمیم نہیں کی جا سکتی",
    "are_you_sure_delete_role": "کیا آپ واقعی اس رول کو حذف کرنا چاہتے ہیں؟",
    "delete_role_warning": "یہ عمل واپس نہیں کیا جا سکتا۔ اس رول والے صارفین کو دوبارہ تفویض کرنے کی ضرورت ہوگی۔",
    "permission_groups": "اجازتی گروپس",
    "main_permissions": "بنیادی اجازتیں",
    "other_permissions": "دیگر اجازتیں",
    // "select_all": "تمام منتخب کریں",
    // "deselect_all": "تمام غیر منتخب کریں",
    
    // Permission Categories
    "products_permissions": "مصنوعات",
    "invoices_permissions": "انوائسز",
    "purchases_permissions": "خریداریاں",
    "customers_permissions": "گاہک",
    "suppliers_permissions": "سپلائرز",
    "categories_permissions": "زمرہ جات",
    "reports_permissions": "رپورٹس",
    "users_permissions": "صارفین",
    "roles_permissions_group": "رولز",
    "settings_permissions": "ترتیبات",
    "dashboard_permissions": "ڈیش بورڈ",
    "payments_permissions": "ادائیگیاں",
    
    // Individual Permissions
    "viewProducts": "مصنوعات دیکھیں",
    "createProducts": "مصنوعات بنائیں",
    "editProducts": "مصنوعات میں ترمیم کریں",
    "deleteProducts": "مصنوعات حذف کریں",
    "viewInvoices": "انوائسز دیکھیں",
    "createInvoices": "انوائسز بنائیں",
    "editInvoices": "انوائسز میں ترمیم کریں",
    "deleteInvoices": "انوائسز حذف کریں",
    "viewPurchases": "خریداریاں دیکھیں",
    "createPurchases": "خریداریاں بنائیں",
    "editPurchases": "خریداریوں میں ترمیم کریں",
    "deletePurchases": "خریداریاں حذف کریں",
    "viewCustomers": "گاہک دیکھیں",
    "createCustomers": "گاہک شامل کریں",
    "editCustomers": "گاہک میں ترمیم کریں",
    "deleteCustomers": "گاہک حذف کریں",
    "viewSuppliers": "سپلائرز دیکھیں",
    "createSuppliers": "سپلائرز شامل کریں",
    "editSuppliers": "سپلائرز میں ترمیم کریں",
    "deleteSuppliers": "سپلائرز حذف کریں",
    "viewCategories": "زمرہ جات دیکھیں",
    "createCategories": "زمرہ جات بنائیں",
    "editCategories": "زمرہ جات میں ترمیم کریں",
    "deleteCategories": "زمرہ جات حذف کریں",
    "viewReports": "رپورٹس دیکھیں",
    "exportReports": "رپورٹس ایکسپورٹ کریں",
    "viewUsers": "صارفین دیکھیں",
    "createUsers": "صارفین بنائیں",
    "editUsers": "صارفین میں ترمیم کریں",
    "deleteUsers": "صارفین حذف کریں",
    "viewRoles": "رولز دیکھیں",
    "createRoles": "رولز بنائیں",
    "editRoles": "رولز میں ترمیم کریں",
    "deleteRoles": "رولز حذف کریں",
    "viewSettings": "ترتیبات دیکھیں",
    "editSettings": "ترتیبات میں ترمیم کریں",
    "viewDashboard": "ڈیش بورڈ دیکھیں",
    "managePayments": "ادائیگیوں کا انتظام کریں",
    
    // Users Management
    "users_management": "صارفین کا انتظام",
    "users_management_description": "صارفین کا انتظام کریں اور رولز تفویض کریں",
    "all_users": "تمام صارفین",
    "users_list_description": "تمام سسٹم صارفین دیکھیں اور ان کا انتظام کریں",
    "no_users_found": "کوئی صارف نہیں ملا",
    "create_user": "صارف بنائیں",
    "edit_user": "صارف میں ترمیم کریں",
    "delete_user": "صارف حذف کریں",
    "user_created_successfully": "صارف کامیابی سے بنایا گیا",
    "user_updated_successfully": "صارف کامیابی سے اپ ڈیٹ ہو گیا",
    "user_deleted_successfully": "صارف کامیابی سے حذف ہو گیا",
    "failed_to_save_user": "صارف محفوظ کرنے میں ناکام",
    "failed_to_delete_user": "صارف حذف کرنے میں ناکام",
    "enter_user_name": "صارف کا نام درج کریں",
    "enter_email": "ای میل درج کریں",
    "enter_password": "پاس ورڈ درج کریں",
    "new_password": "نیا پاس ورڈ (اختیاری)",
    "leave_blank_to_keep": "موجودہ رکھنے کے لیے خالی چھوڑیں",
    "select_role": "رول منتخب کریں",
    "create_user_description": "سسٹم میں نیا صارف شامل کریں اور رول تفویض کریں",
    "edit_user_description": "صارف کی معلومات اپ ڈیٹ کریں اور رول تفویض کریں",
    "delete_user_confirmation": "کیا آپ واقعی اس صارف کو حذف کرنا چاہتے ہیں؟ یہ عمل واپس نہیں کیا جا سکتا۔",
    "no_role": "کوئی رول نہیں",
    "verified": "تصدیق شدہ",
    "not_verified": "غیر تصدیق شدہ",
    "email_verified": "ای میل تصدیق شدہ",
    "return_clear_filters": "فلٹرز صاف کریں",
    "return_all_statuses": "تمام حالات",
    "return_all_types": "تمام اقسام",
    "loading_returns": "واپسیاں لوڈ ہو رہی ہیں...",
    "return_notes": "نوٹس",
    "accounts": "اکاؤنٹس",
    "transactions": "ٹرانزیکشنز",
    "mobile_repairing": "موبائل ریپیئرنگ",
    "jazz_cash_&_load": "جاز کیش اور لوڈ",
    // "reports": "رپورٹس",
    "customers_ledger": "کسٹمر لیجر",
    "suppliers_ledger": "سپلائر لیجر",
    "transaction_ledger": "ٹرانزیکشن لیجر",
    "sale_ledger": "سیل لیجر",
    "purchase_ledger": "پرچیز لیجر",
    "account_ledger": "اکاؤنٹ لیجر",

    // Categories page
    // "categories": "کیٹگریز",
    "manage_product_categories": "یہاں اپنی پروڈکٹ کیٹگریز کا انتظام کریں۔",
    "add_category": "کیٹگری شامل کریں",
    "edit_category": "کیٹگری میں ترمیم کریں",
    "delete_category": "کیٹگری حذف کریں",
    "category_name": "کیٹگری کا نام",
    "category_image": "کیٹگری کی تصویر",
    "enter_category_name": "کیٹگری کا نام داخل کریں",
    "enter_category_description": "کیٹگری کی تفصیل داخل کریں",
    "upload_category_image": "کیٹگری کی تصویر اپ لوڈ کریں",
    "optional": "اختیاری",
    
    // Category CRUD operations
    "category_created_successfully": "کیٹگری کامیابی سے بنائی گئی",
    "category_updated_successfully": "کیٹگری کامیابی سے اپ ڈیٹ ہوگئی",
    "category_deleted_successfully": "کیٹگری کامیابی سے حذف ہوگئی",
    "category_creation_failed": "کیٹگری بنانے میں ناکامی",
    "category_update_failed": "کیٹگری اپ ڈیٹ کرنے میں ناکامی",
    "category_deletion_failed": "کیٹگری حذف کرنے میں ناکامی",
    "update_category_description": "یہاں کیٹگری کو اپ ڈیٹ کریں۔ ہو جانے پر محفوظ کریں۔",
    "create_category_description": "یہاں نئی کیٹگری بنائیں۔ ہو جانے پر محفوظ کریں۔",
    "create_category": "کیٹگری بنائیں",
    "update_category": "کیٹگری اپ ڈیٹ کریں",
    "delete_category_confirmation": "کیا آپ واقعی اس کیٹگری کو حذف کرنا چاہتے ہیں",
    // "saving": "محفوظ کر رہے ہیں...",
    "deleting": "حذف کر رہے ہیں...",
    "failed_to_load_categories": "کیٹگریز لوڈ کرنے میں ناکامی",
    "select_categories": "کیٹگریز منتخب کریں",
    "no_categories_found": "کوئی کیٹگری نہیں ملی",
    
    // Voice Input functionality
    "no_speech_detected": "کوئی آواز کا پتہ نہیں چلا",
    "microphone_not_available": "مائیکروفون دستیاب نہیں",
    "microphone_permission_denied": "مائیکروفون کی اجازت مسترد",
    "network_error_voice_recognition": "آواز کی شناخت میں نیٹ ورک کی خرابی",
    "voice_recognition_error": "آواز کی شناخت میں خرابی",
    "voice_recording_started": "آواز کی ریکارڈنگ شروع ہوگئی",
    "failed_to_start_voice_recording": "آواز کی ریکارڈنگ شروع کرنے میں ناکامی",
    "voice_recording_stopped": "آواز کی ریکارڈنگ رک گئی",
    "start_voice_recording": "آواز کی ریکارڈنگ شروع کریں",
    "stop_voice_recording": "آواز کی ریکارڈنگ رک کریں",
    "voice_recognition_not_supported": "اس براؤزر میں آواز کی شناخت کی سہولت دستیاب نہیں",
    
    // Voice Input Demo
    "voice_input_demo": "آواز سے ٹیکسٹ ڈیمو",
    "test_voice_to_text_functionality": "آواز سے ٹیکسٹ کی فیچر ٹیسٹ کریں",
    "product_information": "پروڈکٹ کی معلومات",
    "voice_input_product_demo_description": "پروڈکٹ کی تفصیلات بھرنے کے لیے بولنے کی کوشش کریں",
    "speak_or_type_product_name": "پروڈکٹ کا نام بولیں یا ٹائپ کریں...",
    "speak_or_type_description": "تفصیل بولیں یا ٹائپ کریں...",
    "additional_notes": "اضافی نوٹس",
    "speak_or_type_notes": "نوٹس بولیں یا ٹائپ کریں...",
    "voice_input_results": "آواز سے ٹیکسٹ کے نتائج",
    "see_converted_text_here": "تبدیل شدہ ٹیکسٹ یہاں دیکھیں",
    "no_text_entered": "ابھی تک کوئی ٹیکسٹ داخل نہیں ہوا",
    "voice_input_instructions": "آواز سے ٹیکسٹ کی ہدایات",
    "click_microphone_icon_to_start": "ریکارڈنگ شروع کرنے کے لیے مائیکروفون آئیکن پر کلک کریں",
    "speak_clearly_into_microphone": "اپنے مائیکروفون میں صاف بولیں",
    "voice_automatically_converts_to_text": "آواز خود کار طریقے سے ٹیکسٹ میں تبدیل ہو جائے گی",
    "click_microphone_again_to_stop": "ریکارڈنگ رکنے کے لیے مائیکروفون آئیکن پر دوبارہ کلک کریں",
    "note": "نوٹ",
    "language_switches_automatically": "زبان کی شناخت آپ کی منتخب کردہ زبان کی بنیاد پر خود کار طریقے سے بدل جاتی ہے",
    
    // Company Profile
    "company_profile": "کمپنی پروفائل",
    "company_setup": "کمپنی سیٹ اپ",
    "manage_your_company_information": "اپنی کمپنی کی معلومات کا انتظام کریں",
    "setup_your_company_profile": "شروع کرنے کے لیے اپنی کمپنی کا پروفائل ترتیب دیں",
    "company_information": "کمپنی کی معلومات",
    "update_your_company_details": "اپنی کمپنی کی تفصیلات اپ ڈیٹ کریں",
    "enter_your_company_details_to_get_started": "شروع کرنے کے لیے اپنی کمپنی کی تفصیلات درج کریں",
    "company_name": "کمپنی کا نام",
    "tax_number": "ٹیکس نمبر",
    "address_information": "پتہ کی معلومات",
    "change_password": "پاس ورڈ تبدیل کریں",
    "change_your_company_password": "اپنی کمپنی کا پاس ورڈ تبدیل کریں",
    "current_password": "موجودہ پاس ورڈ",
    // "new_password": "نیا پاس ورڈ",
    "confirm_new_password": "نئے پاس ورڈ کی تصدیق کریں",
    "confirm_password": "پاس ورڈ کی تصدیق کریں",
    "changing": "تبدیل ہو رہا ہے...",
    "create_company_profile": "کمپنی پروفائل بنائیں",
    "enter_company_name": "کمپنی کا نام درج کریں",
    // "enter_email": "ای میل درج کریں",
    // "enter_password": "پاس ورڈ درج کریں",
    "enter_phone": "فون نمبر درج کریں",
    "enter_tax_number": "ٹیکس نمبر درج کریں",
    "enter_address": "پتہ درج کریں",
    "enter_city": "شہر درج کریں",
    "enter_country": "ملک درج کریں",
    "Passwords do not match": "پاس ورڈ مماثل نہیں ہیں",
    "Password must be at least 8 characters": "پاس ورڈ کم از کم 8 حروف کا ہونا چاہیے",
    "Company profile updated successfully": "کمپنی کا پروفائل کامیابی سے اپ ڈیٹ ہوا",
    "Failed to update company profile": "کمپنی کا پروفائل اپ ڈیٹ کرنے میں ناکامی",
    "Password changed successfully": "پاس ورڈ کامیابی سے تبدیل ہوا",
    "Failed to change password": "پاس ورڈ تبدیل کرنے میں ناکامی",
    "Company profile created successfully": "کمپنی کا پروفائل کامیابی سے بنایا گیا",
    "Failed to create company profile": "کمپنی کا پروفائل بنانے میں ناکامی",
  }
}

// Interface for our context
interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
  isRTL: boolean
}

// Create context with default values
const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
  isRTL: false
})

// Hook for using the language context
export const useLanguage = () => useContext(LanguageContext)

// Provider component
export function LanguageProvider({ children }: { children: ReactNode }) {
  // Initialize language from localStorage or default to English
  const [language, setLanguage] = useState<Language>(
    () => (localStorage.getItem('language') as Language) || 'en'
  )
  
  // Determine if current language is RTL
  const isRTL = language === 'ur'
  
  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || key
  }
  
  // Save language to localStorage when it changes
  useEffect(() => {
    localStorage.setItem('language', language)
  }, [language])
  
  // Apply font changes based on language (without changing direction)
  useEffect(() => {
    const root = document.documentElement
    const body = document.body
    
    // Set language attribute properly for each language
    if (language === 'ur') {
      root.setAttribute('lang', 'ur')
      body.setAttribute('lang', 'ur')
      // Add notranslate class and attributes to prevent Google Translate from translating Urdu content
      root.classList.add('notranslate')
      body.classList.add('notranslate')
      root.setAttribute('translate', 'no')
      body.setAttribute('translate', 'no')
      // Apply Urdu font
      document.body.style.fontFamily = "'Noto Nastaliq Urdu', system-ui, sans-serif"
    } else {
      root.setAttribute('lang', 'en')
      body.setAttribute('lang', 'en')
      // Remove notranslate class for English
      root.classList.remove('notranslate')
      body.classList.remove('notranslate')
      root.removeAttribute('translate')
      body.removeAttribute('translate')
      // For English, use default font
      document.body.style.fontFamily = "system-ui, sans-serif"
    }
    
    // Always use LTR direction
    root.setAttribute('dir', 'ltr')
    root.classList.add('ltr')
    root.classList.remove('rtl')
  }, [language])
  
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  )
}
