module.exports.Token = require('./token.model');
module.exports.User = require('./user.model');
module.exports.Role = require('./role.model');
module.exports.Customer = require('./customer.model');
module.exports.Supplier = require('./supplier.model');
module.exports.Product = require('./product.model');
module.exports.Category = require('./category.model');
module.exports.Purchase = require('./purchase.model');
module.exports.Invoice = require('./invoice.model');
module.exports.GeneralLedger = require('./generalLedger.model');
module.exports.Voucher = require('./voucher.model');
module.exports.Expense = require('./expense.model');
module.exports.CustomerLedger = require('./customerLedger.model');
module.exports.SupplierLedger = require('./supplierLedger.model');
module.exports.Company = require('./company.model');

// HR Models
module.exports.Employee = require('./employee.model');
module.exports.Department = require('./department.model');
module.exports.Designation = require('./designation.model');
module.exports.Shift = require('./shift.model');
module.exports.Attendance = require('./attendance.model');
module.exports.Leave = require('./leave.model');
module.exports.Payroll = require('./payroll.model');
module.exports.PerformanceReview = require('./performanceReview.model');