const mongoose = require('mongoose');
const { toJSON, paginate } = require('./plugins');

const TRANSFER_STATUSES = [
  'suggested', // generated by the purchase-suggestions engine, not yet acted on
  'approved', // a user accepted the suggestion / created it manually
  'in_transit', // stock has left the source branch
  'completed', // stock received at destination branch (and applied to stockQuantity)
  'cancelled',
];

/**
 * Represents a recommendation (or executed action) to move stock of the same
 * product from a branch with surplus to a branch with a shortage, instead of
 * placing a new purchase order. `fromProductId`/`toProductId` are separate because
 * Product documents are branch-scoped (each branch owns its own Product doc, even
 * for "the same" item) — they're matched by barcode/name in the suggestion engine.
 */
const InventoryTransferSchema = new mongoose.Schema(
  {
    organizationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Organization',
      required: true,
      index: true,
    },
    fromBranchId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Branch',
      required: true,
      index: true,
    },
    toBranchId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Branch',
      required: true,
      index: true,
    },
    fromProductId: { type: mongoose.Schema.Types.ObjectId, ref: 'Product', required: true },
    toProductId: { type: mongoose.Schema.Types.ObjectId, ref: 'Product', required: true },
    productName: { type: String, trim: true }, // snapshot for display

    // Set when the transferred item is a real (or batch/expiry-tracked default) variant —
    // stock for those lives in Inventory, not Product.stockQuantity, see
    // docs/architecture/universal-product-migration.md. Both null for a plain product.
    fromVariantId: { type: mongoose.Schema.Types.ObjectId, ref: 'ProductVariant' },
    toVariantId: { type: mongoose.Schema.Types.ObjectId, ref: 'ProductVariant' },

    // Snapshot of the specific batch depleted at the source, captured at creation time
    // so completion can credit an equivalent batch at the destination even if the
    // source batch is later fully depleted/written off.
    batchSnapshot: {
      batchId: { type: mongoose.Schema.Types.ObjectId, ref: 'Batch' },
      batchNumber: { type: String, trim: true },
      costPerUnit: { type: Number },
      sellingPrice: { type: Number },
      expiryDate: { type: Date },
    },

    quantity: { type: Number, required: true, min: 1 },

    reason: { type: String, trim: true }, // human-readable justification, e.g. "Lahore has 100 units, Karachi has 5 and is selling 8/day"

    status: {
      type: String,
      enum: TRANSFER_STATUSES,
      default: 'suggested',
      index: true,
    },

    suggestedAt: { type: Date, default: Date.now },
    decidedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    decidedAt: { type: Date },
    completedAt: { type: Date },

    notes: { type: String, trim: true },
  },
  { timestamps: true },
);

InventoryTransferSchema.index({ organizationId: 1, status: 1, suggestedAt: -1 });
InventoryTransferSchema.index({ organizationId: 1, fromBranchId: 1, toBranchId: 1 });

InventoryTransferSchema.plugin(toJSON);
InventoryTransferSchema.plugin(paginate);

InventoryTransferSchema.statics.STATUSES = TRANSFER_STATUSES;

const InventoryTransfer = mongoose.model('InventoryTransfer', InventoryTransferSchema);

module.exports = InventoryTransfer;
module.exports.TRANSFER_STATUSES = TRANSFER_STATUSES;
