import { createFileRoute } from '@tanstack/react-router'
import FastBillingPage from '@/features/fast-billing'

// @ts-ignore - Route will be generated by TanStack Router plugin
export const Route = createFileRoute('/_authenticated/fast-billing/')({
  component: FastBillingPage,
})
