import { createApi } from '@reduxjs/toolkit/query/react'
import { baseQuery } from './base-query'
import { mobileShopApi } from './mobile-shop.api'

/** Paying an expense posts a cash-book entry server-side, but expenseApi is a separate
 *  RTK Query slice from mobileShopApi (which owns the Cash Book page's cache), so that
 *  page would otherwise keep showing stale totals until a full reload. */
const invalidateCashBook = async (_arg: unknown, { dispatch, queryFulfilled }: any) => {
  try {
    await queryFulfilled
    dispatch(mobileShopApi.util.invalidateTags(['CashBook', 'MobileDashboard']))
  } catch {
    // mutation failed — nothing to invalidate
  }
}

export interface ExpenseRecord {
  id: string
  expenseNumber?: string
  category: string
  description: string
  amount: number
  paymentMethod: string
  walletType?: string
  vendor?: string
  date: string
  reference?: string
  referenceId?: string
  referenceModel?: string
  notes?: string
  isPaid: boolean
  paidAt?: string | null
  createdAt: string
}

export interface PayBulkResult {
  matched: number
  paidCount: number
  totalAmount: number
  errors: { id: string; message: string }[]
}

interface PaginatedResult<T> {
  results: T[]
  page: number
  limit: number
  totalPages: number
  totalResults: number
}

export const expenseApi = createApi({
  reducerPath: 'expenseApi',
  baseQuery,
  tagTypes: ['Expenses'],
  endpoints: (builder) => ({
    /** Unpaid expenses generated by a specific recurring rule (or org-wide if no referenceId given) — used to list individual items before bulk/single pay. */
    getPendingExpenses: builder.query<PaginatedResult<ExpenseRecord>, { referenceId?: string } | void>({
      query: (params) => ({
        url: '/expenses',
        params: {
          isPaid: false,
          referenceModel: 'RecurringExpense',
          sortBy: 'date:asc',
          limit: 200,
          ...(params?.referenceId ? { referenceId: params.referenceId } : {}),
        },
      }),
      providesTags: ['Expenses'],
    }),
    payExpense: builder.mutation<ExpenseRecord, string>({
      query: (expenseId) => ({ url: `/expenses/${expenseId}/pay`, method: 'PATCH' }),
      invalidatesTags: ['Expenses'],
      onQueryStarted: invalidateCashBook,
    }),
    payExpensesBulk: builder.mutation<PayBulkResult, { referenceId?: string; category?: string; all?: boolean }>({
      query: (body) => ({ url: '/expenses/pay-bulk', method: 'POST', body }),
      invalidatesTags: ['Expenses'],
      onQueryStarted: invalidateCashBook,
    }),
  }),
})

export const {
  useGetPendingExpensesQuery,
  usePayExpenseMutation,
  usePayExpensesBulkMutation,
} = expenseApi
