export type InvoiceLanguage = 'en' | 'ur'

export interface InvoiceLanguageContext {
  language?: InvoiceLanguage
  isUrduOnly?: boolean
  userPreferredLanguage?: InvoiceLanguage
}

export const resolveInvoiceLanguage = ({
  language,
  isUrduOnly,
  userPreferredLanguage,
}: InvoiceLanguageContext): InvoiceLanguage => {
  if (isUrduOnly) return 'ur'
  return language ?? userPreferredLanguage ?? 'en'
}

const sharedLabels = {
  en: {
    cash: 'Cash',
    credit: 'Credit',
    pending: 'Pending',
    powered_by: 'Logix Plus Software Solutions',
  },
  ur: {
    cash: 'کیش',
    credit: 'ادھار',
    pending: 'زیر التوا',
    powered_by: 'Logix Plus Software Solutions',
  },
} as const

export const receiptLabels = {
  en: {
    business_name: 'Your Business',
    business_address: 'Your address, city, country',
    business_phone: '+92 300 1234567',
    business_email: 'info@yourbusiness.com',
    tax_id_prefix: 'Tax ID:',
    tax_id_fallback: '123456789',
    invoice_title: 'Invoice Receipt',
    invoice_number: 'Invoice Number',
    date: 'Date',
    time: 'Time',
    type: 'Type',
    customer: 'Customer',
    due_date: 'Due Date',
    walk_in_customer: 'Walk-in Customer',
    items_purchased: 'Items Purchased',
    subtotal: 'Subtotal',
    discount: 'Discount',
    delivery_charge: 'Delivery Charge',
    service_charge: 'Service Charge',
    tax: 'Tax',
    total: 'Total',
    paid: 'Paid',
    balance_due: 'Balance Due',
    paid_in_full: 'Paid in Full',
    previous_balance: 'Previous Balance',
    current_invoice: 'Current Invoice',
    net_balance: 'Net Balance',
    notes: 'Notes',
    thank_you: 'Thank you!',
    keep_receipt: 'Please keep this receipt for your records',
    visit_again: 'We look forward to serving you again',
    print_options: 'Print Options',
    print_receipt: 'Print Receipt',
    close: 'Close',
    not_available: 'N/A',
    ...sharedLabels.en,
  },
  ur: {
    business_name: 'آپ کا کاروبار',
    business_address: 'آپ کا پتہ، شہر، ملک',
    business_phone: '+92 300 1234567',
    business_email: 'info@yourbusiness.com',
    tax_id_prefix: 'ٹیکس آئی ڈی:',
    tax_id_fallback: '123456789',
    invoice_title: 'رسید',
    invoice_number: 'رسید نمبر',
    date: 'تاریخ',
    time: 'وقت',
    type: 'قسم',
    customer: 'کسٹمر',
    due_date: 'آخری تاریخ',
    walk_in_customer: 'واک ان کسٹمر',
    items_purchased: 'خریدی گئی اشیاء',
    subtotal: 'ذیلی ٹوٹل',
    discount: 'رعایت',
    delivery_charge: 'ڈیلیوری چارج',
    service_charge: 'سروس چارج',
    tax: 'ٹیکس',
    total: 'کل',
    paid: 'ادا شدہ',
    balance_due: 'باقی رقم',
    paid_in_full: 'مکمل ادائیگی',
    previous_balance: 'پچھلا بیلنس',
    current_invoice: 'موجودہ انوائس',
    net_balance: 'کل بیلنس',
    notes: 'نوٹس',
    thank_you: 'آپ کا شکریہ!',
    keep_receipt: 'براہ کرم یہ رسید محفوظ رکھیں',
    visit_again: 'دوبارہ تشریف لائیے گا',
    print_options: 'پرنٹ آپشنز',
    print_receipt: 'رسید پرنٹ کریں',
    close: 'بند کریں',
    not_available: 'دستیاب نہیں',
    ...sharedLabels.ur,
  },
} as const

export const a4Labels = {
  en: {
    business_name: 'Your Business',
    business_address: 'Your address, city, country',
    business_phone: '+92 300 1234567',
    business_email: 'info@yourbusiness.com',
    tax_id_prefix: 'Tax ID:',
    tax_id_fallback: '123456789',
    invoice_title: 'Invoice',
    invoice_number: 'Invoice Number',
    date: 'Date',
    time: 'Time',
    type: 'Type',
    customer: 'Customer',
    due_date: 'Due Date',
    walk_in_customer: 'Walk-in Customer',
    bill_to: 'Bill To',
    invoice_details: 'Invoice Details',
    issue_date: 'Issue Date',
    items_count: 'Items Count',
    product_name: 'Product Name',
    quantity: 'Quantity',
    unit_price: 'Unit Price',
    total_amount: 'Total Amount',
    subtotal: 'Subtotal',
    discount: 'Discount',
    delivery_charge: 'Delivery Charge',
    service_charge: 'Service Charge',
    tax: 'Tax',
    total: 'Total',
    amount: 'Amount',
    payment_information: 'Payment Information',
    amount_paid: 'Amount Paid',
    balance_due: 'Balance Due',
    paid_in_full: 'Paid in Full',
    payment_status: 'Payment Status',
    completed: 'Completed',
    pending_payment: 'Payment Pending',
    previous_balance: 'Previous Balance',
    current_invoice: 'Current Invoice',
    net_balance: 'Net Balance',
    invoice_barcode: 'Invoice Barcode',
    scan_to_verify: 'Scan to verify',
    additional_notes: 'Additional Notes',
    thank_you: 'Thank you!',
    keep_receipt: 'Please keep this invoice for your records',
    generated_on: 'Generated On',
    print_options: 'Print Options',
    print_invoice: 'Print Invoice',
    close: 'Close',
    not_available: 'N/A',
    ...sharedLabels.en,
  },
  ur: {
    business_name: 'آپ کا کاروبار',
    business_address: 'آپ کا پتہ، شہر، ملک',
    business_phone: '+92 300 1234567',
    business_email: 'info@yourbusiness.com',
    tax_id_prefix: 'ٹیکس آئی ڈی:',
    tax_id_fallback: '123456789',
    invoice_title: 'انوائس',
    invoice_number: 'انوائس نمبر',
    date: 'تاریخ',
    time: 'وقت',
    type: 'قسم',
    customer: 'کسٹمر',
    due_date: 'آخری تاریخ',
    walk_in_customer: 'واک ان کسٹمر',
    bill_to: 'بل کی معلومات',
    invoice_details: 'انوائس کی تفصیلات',
    issue_date: 'تاریخ',
    items_count: 'اشیاء کی تعداد',
    product_name: 'پروڈکٹ کا نام',
    quantity: 'مقدار',
    unit_price: 'قیمت',
    total_amount: 'کل رقم',
    subtotal: 'ذیلی ٹوٹل',
    discount: 'رعایت',
    delivery_charge: 'ڈیلیوری چارج',
    service_charge: 'سروس چارج',
    tax: 'ٹیکس',
    total: 'کل',
    amount: 'رقم',
    payment_information: 'ادائیگی کی معلومات',
    amount_paid: 'ادا شدہ رقم',
    balance_due: 'باقی رقم',
    paid_in_full: 'مکمل ادائیگی',
    payment_status: 'ادائیگی کی صورتحال',
    completed: 'مکمل',
    pending_payment: 'ادائیگی باقی',
    previous_balance: 'پچھلا بیلنس',
    current_invoice: 'موجودہ انوائس',
    net_balance: 'کل بیلنس',
    invoice_barcode: 'انوائس بار کوڈ',
    scan_to_verify: 'تصدیق کے لیے اسکین کریں',
    additional_notes: 'اضافی نوٹس',
    thank_you: 'آپ کا شکریہ!',
    keep_receipt: 'براہ کرم یہ انوائس محفوظ رکھیں',
    generated_on: 'تیار کیا گیا',
    print_options: 'پرنٹ آپشنز',
    print_invoice: 'انوائس پرنٹ کریں',
    close: 'بند کریں',
    not_available: 'دستیاب نہیں',
    ...sharedLabels.ur,
  },
} as const
