export type InvoiceLanguage = 'en' | 'ur'

export interface InvoiceLanguageContext {
  language?: InvoiceLanguage
  isUrduOnly?: boolean
  userPreferredLanguage?: InvoiceLanguage
}

export const resolveInvoiceLanguage = ({
  language,
  isUrduOnly,
  userPreferredLanguage,
}: InvoiceLanguageContext): InvoiceLanguage => {
  if (isUrduOnly) return 'ur'
  return language ?? userPreferredLanguage ?? 'en'
}

const sharedLabels = {
  en: {
    cash: 'Cash',
    credit: 'Credit',
    pending: 'Pending',
    contact_label: 'Contact',
    powered_by: 'Logix Plus Software Solutions',
  },
  ur: {
    cash: 'کیش',
    credit: 'ادھار',
    pending: 'زیر التوا',
    contact_label: 'رابطہ',
    powered_by: 'Logix Plus Software Solutions',
  },
} as const

export const receiptLabels = {
  en: {
    business_name: 'Your Business',
    business_address: 'Your address, city, country',
    business_phone: '+92 300 1234567',
    business_email: 'info@yourbusiness.com',
    tax_id_prefix: 'Tax ID:',
    tax_id_fallback: '123456789',
    invoice_title: 'Invoice Receipt',
    quotation_title: 'Quotation',
    invoice_number: 'Invoice Number',
    quotation_number: 'Quotation No',
    date: 'Date',
    time: 'Time',
    type: 'Type',
    customer: 'Customer',
    due_date: 'Due Date',
    invoice_address: 'Address',
    walk_in_customer: 'Walk-in Customer',
    items_purchased: 'Items Purchased',
    product: 'Product',
    price: 'Sale Price',
    qty: 'Qty',
    amount: 'Amount',
    total_receivable: 'Total Receivable',
    customer_receipt: 'Customer Receipt',
    subtotal: 'Subtotal',
    discount: 'Discount',
    delivery_charge: 'Delivery Charge',
    service_charge: 'Service Charge',
    tax: 'Tax',
    total: 'Total',
    paid: 'Paid',
    balance_due: 'Balance Due',
    paid_in_full: 'Paid in Full',
    previous_balance: 'Previous Balance',
    current_invoice: 'Current Amount',
    net_balance: 'Net Balance',
    notes: 'Notes',
    terms_and_conditions: 'Terms & Conditions',
    thank_you: 'Thank you!',
    keep_receipt: 'Please keep this receipt for your records',
    visit_again: 'We look forward to serving you again',
    print_options: 'Print Options',
    print_receipt: 'Print Receipt',
    close: 'Close',
    not_available: 'N/A',
    ...sharedLabels.en,
  },
  ur: {
    business_name: 'آپ کا کاروبار',
    business_address: 'آپ کا پتہ، شہر، ملک',
    business_phone: '+92 300 1234567',
    business_email: 'info@yourbusiness.com',
    tax_id_prefix: 'ٹیکس آئی ڈی:',
    tax_id_fallback: '123456789',
    invoice_title: 'رسید',
    quotation_title: 'کوٹیشن',
    invoice_number: 'رسید نمبر',
    quotation_number: 'کوٹیشن نمبر',
    date: 'تاریخ',
    time: 'وقت',
    type: 'قسم',
    customer: 'کسٹمر',
    due_date: 'آخری تاریخ',
    invoice_address: 'پتہ',
    walk_in_customer: 'واک ان کسٹمر',
    items_purchased: 'خریدی گئی اشیاء',
    product: 'پروڈکٹ',
    price: 'قیمت',
    qty: 'مقدار',
    amount: 'رقم',
    total_receivable: 'کل وصولی',
    customer_receipt: 'کسٹمر رسید',
    subtotal: 'ذیلی ٹوٹل',
    discount: 'رعایت',
    delivery_charge: 'ڈیلیوری چارج',
    service_charge: 'سروس چارج',
    tax: 'ٹیکس',
    total: 'کل',
    paid: 'ادا شدہ',
    balance_due: 'باقی رقم',
    paid_in_full: 'مکمل ادائیگی',
    previous_balance: 'پچھلا بیلنس',
    current_invoice: 'موجودہ رقم',
    net_balance: 'کل بیلنس',
    notes: 'نوٹس',
    terms_and_conditions: 'شرائط و ضوابط',
    thank_you: 'آپ کا شکریہ!',
    keep_receipt: 'براہ کرم یہ رسید محفوظ رکھیں',
    visit_again: 'دوبارہ تشریف لائیے گا',
    print_options: 'پرنٹ آپشنز',
    print_receipt: 'رسید پرنٹ کریں',
    close: 'بند کریں',
    not_available: 'دستیاب نہیں',
    ...sharedLabels.ur,
  },
} as const

export const a4Labels = {
  en: {
    business_name: 'Your Business',
    business_address: 'Your address, city, country',
    business_phone: '+92 300 1234567',
    business_email: 'info@yourbusiness.com',
    tax_id_prefix: 'Tax ID:',
    tax_id_fallback: '123456789',
    invoice_title: 'Invoice',
    quotation_title: 'Quotation',
    invoice_number: 'Invoice Number',
    quotation_number: 'Quotation No',
    date: 'Date',
    time: 'Time',
    type: 'Type',
    customer: 'Customer',
    due_date: 'Due Date',
    invoice_address: 'Address',
    walk_in_customer: 'Walk-in Customer',
    bill_to: 'Bill To',
    billed_to: 'Billed To',
    invoice_details: 'Invoice Details',
    quotation_details: 'Quotation Details',
    issue_date: 'Issue Date',
    items_count: 'Items Count',
    product_name: 'Product Name',
    quantity: 'Quantity',
    unit_price: 'Unit Sale Price',
    total_amount: 'Total Amount',
    subtotal: 'Subtotal',
    discount: 'Discount',
    delivery_charge: 'Delivery Charge',
    service_charge: 'Service Charge',
    tax: 'Tax',
    total: 'Total',
    amount: 'Amount',
    payment_information: 'Payment Information',
    amount_paid: 'Amount Paid',
    balance_due: 'Balance Due',
    paid_in_full: 'Paid in Full',
    payment_status: 'Payment Status',
    completed: 'Completed',
    pending_payment: 'Payment Pending',
    previous_balance: 'Previous Balance',
    current_invoice: 'Current Amount',
    total_receivable: 'Total Receivable',
    net_balance: 'Net Balance',
    invoice_barcode: 'Invoice Barcode',
    scan_to_verify: 'Scan to verify',
    continuation: 'Continuation',
    page_indicator: 'Page {page} of {total}',
    previous_pages_items_total: 'Previous pages (line items)',
    this_page_items_total: 'This page (line items)',
    running_items_total: 'Running total (line items)',
    additional_notes: 'Additional Notes',
    terms_and_conditions: 'Terms & Conditions',
    thank_you: 'Thank you!',
    keep_receipt: 'Please keep this invoice for your records',
    generated_on: 'Generated On',
    print_options: 'Print Options',
    print_invoice: 'Print Invoice',
    close: 'Close',
    not_available: 'N/A',
    ...sharedLabels.en,
  },
  ur: {
    business_name: 'آپ کا کاروبار',
    business_address: 'آپ کا پتہ، شہر، ملک',
    business_phone: '+92 300 1234567',
    business_email: 'info@yourbusiness.com',
    tax_id_prefix: 'ٹیکس آئی ڈی:',
    tax_id_fallback: '123456789',
    invoice_title: 'انوائس',
    quotation_title: 'کوٹیشن',
    invoice_number: 'انوائس نمبر',
    quotation_number: 'کوٹیشن نمبر',
    date: 'تاریخ',
    time: 'وقت',
    type: 'قسم',
    customer: 'کسٹمر',
    due_date: 'آخری تاریخ',
    invoice_address: 'پتہ',
    walk_in_customer: 'واک ان کسٹمر',
    bill_to: 'بل کی معلومات',
    billed_to: 'بل وصول کنندہ',
    invoice_details: 'انوائس کی تفصیلات',
    quotation_details: 'کوٹیشن کی تفصیلات',
    issue_date: 'تاریخ',
    items_count: 'اشیاء کی تعداد',
    product_name: 'پروڈکٹ کا نام',
    quantity: 'مقدار',
    unit_price: 'قیمت',
    total_amount: 'کل رقم',
    subtotal: 'ذیلی ٹوٹل',
    discount: 'رعایت',
    delivery_charge: 'ڈیلیوری چارج',
    service_charge: 'سروس چارج',
    tax: 'ٹیکس',
    total: 'کل',
    amount: 'رقم',
    payment_information: 'ادائیگی کی معلومات',
    amount_paid: 'ادا شدہ رقم',
    balance_due: 'باقی رقم',
    paid_in_full: 'مکمل ادائیگی',
    payment_status: 'ادائیگی کی صورتحال',
    completed: 'مکمل',
    pending_payment: 'ادائیگی باقی',
    previous_balance: 'پچھلا بیلنس',
    current_invoice: 'موجودہ رقم',
    total_receivable: 'کل وصولی',
    net_balance: 'کل بیلنس',
    invoice_barcode: 'انوائس بار کوڈ',
    scan_to_verify: 'تصدیق کے لیے اسکین کریں',
    continuation: 'جاری',
    page_indicator: 'صفحہ {page} از {total}',
    previous_pages_items_total: 'پچھلے صفحات (اشیاء)',
    this_page_items_total: 'یہ صفحہ (اشیاء)',
    running_items_total: 'کل تک کا مجموعہ (اشیاء)',
    additional_notes: 'اضافی نوٹس',
    terms_and_conditions: 'شرائط و ضوابط',
    thank_you: 'آپ کا شکریہ!',
    keep_receipt: 'براہ کرم یہ انوائس محفوظ رکھیں',
    generated_on: 'تیار کیا گیا',
    print_options: 'پرنٹ آپشنز',
    print_invoice: 'انوائس پرنٹ کریں',
    close: 'بند کریں',
    not_available: 'دستیاب نہیں',
    ...sharedLabels.ur,
  },
} as const

// ── Purchase Invoice Labels (80mm receipt) ──
export const purchaseReceiptLabels = {
  en: {
    purchase_invoice: 'Purchase Invoice',
    invoice_number: 'Invoice Number',
    date: 'Date',
    time: 'Time',
    supplier: 'Supplier',
    payment_type: 'Payment Type',
    items_purchased: 'Items Purchased',
    item: 'Item',
    qty: 'Qty',
    price: 'Sale Price',
    subtotal: 'Subtotal',
    total: 'Total',
    paid: 'Paid',
    balance_due: 'Balance Due',
    paid_in_full: 'Paid in Full',
    notes: 'Notes',
    thank_you: 'Thank you for your business!',
    keep_receipt: 'Please keep this receipt for your records',
    print_receipt: 'Print Receipt',
    close: 'Close',
    print_options: 'Print Options',
    not_available: 'N/A',
    ...sharedLabels.en,
  },
  ur: {
    purchase_invoice: 'خریداری رسید',
    invoice_number: 'رسید نمبر',
    date: 'تاریخ',
    time: 'وقت',
    supplier: 'سپلائر',
    payment_type: 'ادائیگی کی قسم',
    items_purchased: 'خریدی گئی اشیاء',
    item: 'آئٹم',
    qty: 'مقدار',
    price: 'قیمت',
    subtotal: 'ذیلی ٹوٹل',
    total: 'کل',
    paid: 'ادا شدہ',
    balance_due: 'باقی رقم',
    paid_in_full: 'مکمل ادائیگی',
    notes: 'نوٹس',
    thank_you: 'آپ کا شکریہ!',
    keep_receipt: 'براہ کرم یہ رسید محفوظ رکھیں',
    print_receipt: 'رسید پرنٹ کریں',
    close: 'بند کریں',
    print_options: 'پرنٹ آپشنز',
    not_available: 'دستیاب نہیں',
    ...sharedLabels.ur,
  },
} as const

// ── Repair Receipt Labels (80mm receipt) ──
export const repairReceiptLabels = {
  en: {
    repair_job_card: 'REPAIR JOB CARD',
    date: 'Date',
    time: 'Time',
    status: 'Status',
    payment_method: 'Payment',
    customer_info: 'Customer Info',
    name: 'Name',
    phone: 'Phone',
    device_info: 'Device Info',
    model: 'Model',
    color: 'Color',
    imei_serial: 'IMEI / Serial',
    technician: 'Technician',
    accessories: 'Accessories',
    fault_issue: 'Fault / Issue',
    charges: 'Charges',
    total_charges: 'Total Charges',
    advance_paid: 'Advance Paid',
    balance_due: 'Balance Due',
    fully_paid: 'FULLY PAID',
    customer_signature: 'Customer Signature',
    technician_signature: 'Technician Signature',
    thank_you: 'Thank you for your visit!',
    keep_receipt: 'Please keep this receipt for collection.',
    contact: 'Contact',
    print: 'Print',
    close: 'Close',
    print_options: 'Print Options',
    not_available: 'N/A',
    in_progress: 'In Progress',
    completed: 'Completed',
    delivered: 'Delivered',
    ...sharedLabels.en,
  },
  ur: {
    repair_job_card: 'مرمت جاب کارڈ',
    date: 'تاریخ',
    time: 'وقت',
    status: 'حالت',
    payment_method: 'ادائیگی',
    customer_info: 'کسٹمر کی معلومات',
    name: 'نام',
    phone: 'فون',
    device_info: 'ڈیوائس کی معلومات',
    model: 'ماڈل',
    color: 'رنگ',
    imei_serial: 'IMEI / سیریل',
    technician: 'ٹیکنیشن',
    accessories: 'لوازمات',
    fault_issue: 'خرابی / مسئلہ',
    charges: 'چارجز',
    total_charges: 'کل چارجز',
    advance_paid: 'ایڈوانس ادا شدہ',
    balance_due: 'باقی رقم',
    fully_paid: 'مکمل ادائیگی',
    customer_signature: 'کسٹمر دستخط',
    technician_signature: 'ٹیکنیشن دستخط',
    thank_you: 'تشریف لانے کا شکریہ!',
    keep_receipt: 'براہ کرم یہ رسید جمع کرانے کے لیے محفوظ رکھیں',
    contact: 'رابطہ',
    print: 'پرنٹ',
    close: 'بند کریں',
    print_options: 'پرنٹ آپشنز',
    not_available: 'دستیاب نہیں',
    in_progress: 'جاری',
    completed: 'مکمل',
    delivered: 'ڈیلیور',
    ...sharedLabels.ur,
  },
} as const

export const paymentReceiptLabels = {
  en: {
    payment_receipt: 'Payment Receipt',
    receipt_no: 'Receipt No',
    received_from: 'Received From',
    phone: 'Phone',
    address: 'Address',
    payment_date: 'Payment Date',
    payment_time: 'Time',
    payment_method: 'Payment Method',
    reference: 'Reference',
    description: 'Description',
    previous_balance: 'Previous Balance',
    payment_received: 'Payment Received',
    remaining_balance: 'Remaining Balance',
    receivable: 'Receivable',
    payable: 'Payable',
    settled: 'Settled',
    received_by: 'Received By',
    customer_signature: 'Customer Signature',
    thank_you: 'Thank you for your payment!',
    computer_generated: 'This is a computer generated receipt',
    print_receipt: 'Print Receipt',
    close: 'Close',
    ...sharedLabels.en,
  },
  ur: {
    payment_receipt: 'ادائیگی کی رسید',
    receipt_no: 'رسید نمبر',
    received_from: 'وصول کنندہ',
    phone: 'فون',
    address: 'پتہ',
    payment_date: 'ادائیگی کی تاریخ',
    payment_time: 'وقت',
    payment_method: 'ادائیگی کا طریقہ',
    reference: 'حوالہ',
    description: 'تفصیل',
    previous_balance: 'پچھلا بیلنس',
    payment_received: 'وصول شدہ رقم',
    remaining_balance: 'باقی رقم',
    receivable: 'وصولی',
    payable: 'ادائیگی',
    settled: 'طے شدہ',
    received_by: 'وصول کنندہ',
    customer_signature: 'کسٹمر کے دستخط',
    thank_you: 'آپ کی ادائیگی کا شکریہ!',
    computer_generated: 'یہ کمپیوٹر سے تیار کردہ رسید ہے',
    print_receipt: 'پرنٹ رسید',
    close: 'بند کریں',
    ...sharedLabels.ur,
  },
} as const

export const billReceiptLabels = {
  en: {
    bill_receipt: 'Bill Payment Receipt',
    customer: 'Customer',
    company: 'Company',
    bill_type: 'Bill Type',
    reference_no: 'Reference #',
    bill_amount: 'Bill Amount',
    service_charge: 'Service Charge',
    total_paid: 'Total Paid',
    payment_method: 'Payment Method',
    due_date: 'Due Date',
    payment_date: 'Payment Date',
    status: 'Status',
    thank_you: 'Thank you for using our service!',
    print: 'Print Receipt',
    close: 'Close',
    previous_outstanding: 'Previous Outstanding Bill',
    already_collected: 'Already Collected',
    amount_to_settle: 'Amount Still to Settle',
    overdue_since: 'Overdue Since',
    ...sharedLabels.en,
  },
  ur: {
    bill_receipt: 'بل ادائیگی رسید',
    customer: 'کسٹمر',
    company: 'کمپنی',
    bill_type: 'بل کی قسم',
    reference_no: 'حوالہ نمبر',
    bill_amount: 'بل کی رقم',
    service_charge: 'سروس چارج',
    total_paid: 'کل ادائیگی',
    payment_method: 'ادائیگی کا طریقہ',
    due_date: 'آخری تاریخ',
    payment_date: 'ادائیگی کی تاریخ',
    status: 'حیثیت',
    thank_you: 'ہماری سروس استعمال کرنے کا شکریہ!',
    print: 'پرنٹ رسید',
    close: 'بند کریں',
    previous_outstanding: 'پچھلا واجب الادا بل',
    already_collected: 'وصول شدہ رقم',
    amount_to_settle: 'باقی ادائیگی',
    overdue_since: 'تاخیر کی تاریخ',
    ...sharedLabels.ur,
  },
} as const
