import { createFileRoute } from '@tanstack/react-router'
import { z } from 'zod'
import PurchaseInvoicePage from '@/features/purchase-invoice'

const purchaseInvoiceSearchSchema = z.object({
  supplierId: z.string().optional(),
})

// @ts-ignore - Route will be generated by TanStack Router plugin
export const Route = createFileRoute('/_authenticated/purchase-invoice/')({
  validateSearch: purchaseInvoiceSearchSchema,
  component: PurchaseInvoicePage,
})
