import { createFileRoute } from '@tanstack/react-router'
import PurchaseInvoicePage from '@/features/purchase-invoice'

// @ts-ignore - Route will be generated by TanStack Router plugin
export const Route = createFileRoute('/_authenticated/purchase-invoice/')({
  component: PurchaseInvoicePage,
})
